(() => {
  "use strict";
  const config = window.ALDO_ADMIN_CONFIG || {};
  const db = window.supabase.createClient(config.supabaseUrl, config.supabasePublishableKey);
  const $ = (id) => document.getElementById(id);
  const viewNames = ["home","orders","candidates","stock","items","categories","components","customers","admins"];
  const routeView = location.hash.slice(1);
  const savedView = viewNames.includes(routeView) ? routeView : localStorage.getItem("aldoAdminViewV2");
  const savedOrderTab=Number(localStorage.getItem("aldoAdminOrdersTab")||0);
  const state = {session:null,isAdmin:false,items:[],categories:[],components:[],associations:[],packages:[],packageComponents:[],packagePresentations:[],packageComponentDraft:new Map(),activePackageManagerId:null,activePresentationPackageId:null,itemPackages:[],itemComponentConfigs:[],orders:[],orderLoadRevision:0,candidates:[],liveChannels:[],booting:false,view:viewNames.includes(savedView)?savedView:"home",inventoryDrafts:new Map(),orderTab:[-1,0,1,2].includes(savedOrderTab)?savedOrderTab:0,autoAcceptSiteOrders:true};
  const titles = {home:"Administração",orders:"Pedidos",candidates:"Confirmações IA",stock:"Inventário",items:"Itens",categories:"Categorias",components:"Componentes",customers:"Cadastros",admins:"Administradores"};
  let orderRefreshTimer=null;
  const displayLabels = {lista:"Lista","lista-dupla":"Lista dupla",grade:"Grade",grid:"Grid legado"};
  const linkLabels = {delta:"Ajustável",scalable:"Escalável",complementary:"Complementar"};
  const packageKindLabels={adjustable:"Delta · 0/1/2",scalable:"Escalável",decay:"Decaimento por prioridade",complementary:"Complementar (legado)",single_required:"Escolha única (legado)"};
  const packageAvailabilityLabels={all_positive_defaults_required:"Padrões positivos obrigatórios",one_available_with_priority_fallback:"Obrigatório com prioridade",optional_warn_only:"Opcional com aviso",optional:"Opcional"};

  function toast(message,error=false){const el=$("toast");el.textContent=message;el.style.borderColor=error?"var(--red)":"var(--green)";el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,4200)}
  function money(value){return Number(value||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
  function escapeHtml(value){return String(value??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
  function slug(value){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,40)||"registro"}
  async function query(table,select="*"){const {data,error}=await db.from(table).select(select);if(error)throw error;return data||[]}
  function show(which){$("loadingView").hidden=which!=="loading";$("loginView").hidden=which!=="login";$("deniedView").hidden=which!=="denied";$("appView").hidden=which!=="app"}

  async function bootstrap(){if(state.booting)return;state.booting=true;show("loading");try{const {data:{session}}=await db.auth.getSession();state.session=session;if(!session){show("login");return}const {data,error}=await db.rpc("is_admin");state.isAdmin=!error&&data===true;if(!state.isAdmin){show("denied");return}$("sessionEmail").textContent=session.user.email||"Administrador";await refreshAll();switchView(state.view);subscribe();show("app")}catch(error){show("login");toast(`Não foi possível carregar a sessão: ${error.message}`,true)}finally{state.booting=false}}
  async function login(){await db.auth.signInWithOAuth({provider:"google",options:{redirectTo:location.origin+location.pathname}})}
  async function logout(){await db.auth.signOut();location.reload()}
  async function refreshAll(){try{await Promise.all([loadOrders(),loadCandidates(),loadCatalog(),loadAdmins(),loadCustomers(),loadOrderSettings()])}catch(error){toast(error.message,true)}}

  async function loadOrderSettings(){try{const {data,error}=await db.rpc("get_order_auto_accept");if(error)throw error;state.autoAcceptSiteOrders=data!==false;$("autoAcceptSiteOrders").checked=state.autoAcceptSiteOrders}catch(error){toast(`Configuração de pedidos indisponível: ${error.message}`,true)}}
  async function saveOrderSettings(event){event.preventDefault();const enabled=$("autoAcceptSiteOrders").checked;const {data,error}=await db.rpc("set_order_auto_accept",{p_enabled:enabled});if(error){toast(error.message,true);return}state.autoAcceptSiteOrders=data!==false;$("autoAcceptSiteOrders").checked=state.autoAcceptSiteOrders;$("orderSettingsDialog").close();toast("Configuração salva.")}

  async function loadOrders(){const revision=++state.orderLoadRevision;let orders;try{orders=await query("orders","*,order_items(*,order_item_components(*)),order_sellable_component_totals(*)")}catch(error){if(!/order_sellable_component_totals|relationship|schema cache/i.test(error.message||""))throw error;orders=await query("orders","*,order_items(*,order_item_components(*))")}if(revision!==state.orderLoadRevision)return;state.orders=orders;state.orders.sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));renderOrders()}
  function orderItemMarkup(item,expanded=false){
    const catalogItem=state.items.find(entry=>String(entry.id)===String(item.catalog_item_id||item.item_id))||state.items.find(entry=>entry.name?.trim().toLocaleLowerCase()===String(item.item_name||item.name||"").trim().toLocaleLowerCase());
    const photo=catalogItem?.photo_url_1||catalogItem?.photo_url_2||catalogItem?.photo_url_3;
    const quantity=Math.max(1,Number(item.quantity)||1);
    const rawOptionsText=item.snapshot?.options_text||item.snapshot?.optionsText||item.options_text||item.modifications||"";
    const optionsText=Array.isArray(rawOptionsText)?rawOptionsText.join("|"):rawOptionsText;
    let changes=String(optionsText).split("|").map(part=>part.trim()).filter(Boolean).map(text=>{
      const normalized=text.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase();
      const kind=/^remover\b/.test(normalized)?"remove":/^adicionar\b/.test(normalized)?"add":"other";
      return `<span class="order-change-chip ${kind}">${escapeHtml(text)}</span>`;
    });
    if(!changes.length)changes=(item.order_item_components||[]).filter(component=>{
      const selected=Number(component.snapshot?.per_item_quantity??component.quantity);
      const standard=Number(component.snapshot?.default_quantity??component.free_quantity??0);
      return selected!==standard;
    }).map(component=>{
      const selected=Number(component.snapshot?.per_item_quantity??component.quantity);
      const standard=Number(component.snapshot?.default_quantity??component.free_quantity??0);
      const difference=selected-standard;
      const total=Math.abs(difference)*quantity;
      const prefix=difference>0?"Adicionar":"Remover";
      const amount=total>1?`${total}x `:"";
      return `<span class="order-change-chip ${difference>0?"add":"remove"}">${prefix} ${amount}${escapeHtml(component.component_name)}</span>`;
    });
    const image=photo?`<img src="${escapeHtml(photo)}" alt="" loading="lazy">`:'<span class="order-item-photo" aria-hidden="true"></span>';
    const note=item.notes?`<small>${escapeHtml(item.notes)}</small>`:"";
    const quantityBadge=quantity>1?`<span class="item-quantity-badge" data-quantity="${Math.min(quantity,8)}">${quantity}</span>`:"";
    return `<div class="order-item ${expanded?"expanded-order-item":""}">${image}<div class="order-item-copy"><div class="order-item-title">${quantityBadge}<strong>${escapeHtml(item.item_name||item.name||"Item")}</strong></div>${changes.length?`<div class="order-item-changes">${changes.join("")}</div>`:""}${note}</div></div>`;
  }
  function sellableTotalsMarkup(order){return (order.order_sellable_component_totals||[]).filter(row=>Number(row.quantity)>0).map(row=>{const photo=row.snapshot?.representation?.photo_url_1;return `<div class="order-item pooled-order-component"><span class="order-item-photo" aria-hidden="true">${photo?`<img src="${escapeHtml(photo)}" alt="">`:""}</span><div class="order-item-copy"><strong>${escapeHtml(row.component_name)} ×${Number(row.quantity)}</strong>${row.snapshot?.representation?.description?`<small>${escapeHtml(row.snapshot.representation.description)}</small>`:""}${Number(row.charged_quantity)>0?`<small>${Number(row.charged_quantity)} adicional(is) · ${money(Number(row.charged_quantity)*Number(row.unit_price))}</small>`:""}</div></div>`}).join("")}
  function renderOrders(){
    const pending=state.orders.filter(order=>order.status==="pending_confirmation");
    const pendingCandidates=state.candidates;
    const active=state.orders.filter(order=>["received","confirmed","production"].includes(order.status));
    const deliveryOrders=state.orders.filter(order=>order.status==="delivery");
    const delivered=state.orders.filter(order=>order.status==="delivered").slice().reverse();
    [["pending",pending.length+pendingCandidates.length],["active",active.length],["delivery",deliveryOrders.length],["delivered",delivered.length]].forEach(([key,count])=>{
      const badge=document.querySelector(`[data-order-count="${key}"]`);if(badge)badge.textContent=count;
    });
    $("ordersView").dataset.orderTab=String(state.orderTab);
    document.querySelectorAll("[data-order-tab]").forEach(tab=>{const selected=Number(tab.dataset.orderTab)===state.orderTab;tab.classList.toggle("active",selected);tab.setAttribute("aria-selected",String(selected))});
    const orderCard=(order,tab)=>{
      const address=order.delivery_address||{};
      const location=[address.street,address.landmark,address.address_extra].filter(Boolean).map(escapeHtml).join(" · ");
      const items=(order.order_items||[]).map(item=>orderItemMarkup(item)).join("")+sellableTotalsMarkup(order);
      const generalNote=order.notes?`<p class="order-general-note"><strong>Obs. do pedido:</strong> ${escapeHtml(order.notes)}</p>`:"";
      const canPrepare=["received","confirmed"].includes(order.status),canDeliver=order.status==="production";
      const id=escapeHtml(order.id);
      const actions=tab===-1?`<button class="button order-action review-accept" data-order="${id}" data-status="received" aria-label="Aceitar pedido" title="Aceitar">✓</button><button class="button order-action review-reject" data-order="${id}" data-status="cancelled" aria-label="Recusar pedido" title="Recusar">×</button>`:tab===1?`<button class="button delivery-done icon-action" data-order="${id}" data-status="delivered" aria-label="Marcar como entregue" title="Marcar como entregue"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 6h11v12H3zM14 10h4l3 3v5h-7z"/><circle cx="7.5" cy="19" r="1.5"/><circle cx="18" cy="19" r="1.5"/><path d="m8 11 2 2 4-4"/></svg></button>`:tab===2?"":`<button class="button order-action icon-action" data-order="${id}" data-status="preparing" aria-label="Preparando" title="Preparando" ${canPrepare?"":"disabled"}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 10h16l-1.4 9H5.4L4 10Z"/><path d="M7 7c0-1 1-1 1-2m4 2c0-1 1-1 1-2m4 2c0-1 1-1 1-2M3 21h18"/></svg></button><button class="button order-action icon-action" data-order="${id}" data-status="delivery" aria-label="Saiu para entrega" title="Saiu para entrega" ${canDeliver?"":"disabled"}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 6h11v12H3zM14 10h4l3 3v5h-7z"/><circle cx="7.5" cy="19" r="1.5"/><circle cx="18" cy="19" r="1.5"/><path d="M16 13h4"/></svg></button>`;
      return `<article class="order-row status-${escapeHtml(order.status)}"><div class="order-customer"><strong>${escapeHtml(order.customer_known_as||order.customer_name||"")}</strong>${location?`<small>${location}</small>`:""}<strong class="order-card-total">${money(order.total)}</strong><button class="button view-order-button" data-order-view="${id}">Ver pedido</button></div><div class="order-items">${items}</div><div class="order-actions">${actions}</div>${generalNote}</article>`;
    };
    const candidateCard=candidate=>{
      const detail=candidate.interpreted_order||{};
      const address=detail.delivery_address||{};
      const location=[address.street,address.landmark,address.address_extra].filter(Boolean).map(escapeHtml).join(" · ");
      const items=(Array.isArray(detail.items)?detail.items:[]).map(item=>orderItemMarkup({...item,item_name:item.item_name||item.name,snapshot:item.snapshot||{options_text:item.options_text||item.modifications||""}})).join("");
      const total=Number.isFinite(Number(detail.total))?`<strong class="order-card-total">${money(detail.total)}</strong>`:"";
      const generalNote=detail.notes?`<p class="order-general-note"><strong>Obs. do pedido:</strong> ${escapeHtml(detail.notes)}</p>`:"";
      return `<article class="order-row candidate-order-row status-pending_confirmation"><div class="order-customer"><strong>${escapeHtml(detail.customer_known_as||detail.customer_name||"Pedido WhatsApp")}</strong>${location?`<small>${location}</small>`:""}${total}<button class="button view-order-button" data-candidate-view="${escapeHtml(candidate.id)}">Ver pedido</button></div><div class="order-items">${items}</div><div class="order-actions"><button class="button order-action review-accept" data-candidate-confirm="${escapeHtml(candidate.id)}" aria-label="Confirmar pedido" title="Confirmar">✓</button><button class="button order-action review-reject" data-candidate-discard="${escapeHtml(candidate.id)}" aria-label="Descartar pedido" title="Descartar">×</button></div>${generalNote}</article>`;
    };
    const rows=state.orderTab===-1?[...pending.map(order=>({created_at:order.created_at,html:orderCard(order,-1)})),...pendingCandidates.map(candidate=>({created_at:candidate.created_at,html:candidateCard(candidate)}))].sort((a,b)=>new Date(a.created_at)-new Date(b.created_at)).map(row=>row.html):state.orderTab===1?deliveryOrders.map(order=>orderCard(order,1)):state.orderTab===2?delivered.map(order=>orderCard(order,2)):active.map(order=>orderCard(order,0));
    $("ordersBoard").innerHTML=rows.join("");
    const customerName=order=>escapeHtml(order.customer_known_as||order.customer_name||"");
    const compact=(list)=>list.map(order=>{
      const categoryCounts=new Map();
      (order.order_items||[]).forEach(item=>{
        const category=state.categories.find(entry=>entry.id===state.items.find(catalogItem=>String(catalogItem.id)===String(item.catalog_item_id))?.category_id);
        const categoryName=category?.name||"Sem categoria";
        categoryCounts.set(categoryName,(categoryCounts.get(categoryName)||0)+Number(item.quantity||0));
      });
      const counts=[...categoryCounts].map(([name,quantity])=>`${quantity} ${escapeHtml(name)}`).join(" · ");
      const deliveredAction=list===deliveryOrders?`<button class="button delivery-done icon-action" data-order="${escapeHtml(order.id)}" data-status="delivered" aria-label="Marcar como entregue" title="Marcar como entregue"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 6h11v12H3zM14 10h4l3 3v5h-7z"/><circle cx="7.5" cy="19" r="1.5"/><circle cx="18" cy="19" r="1.5"/><path d="m8 11 2 2 4-4"/></svg></button>`:"";
      const compactState=list===deliveryOrders?"status-delivery":"status-delivered";
      return `<div class="compact-order-name ${compactState} ${deliveredAction?"has-action":""}"><div><strong>${customerName(order)}</strong>${counts?`<small>${counts}</small>`:""}<small class="compact-order-total">${money(order.total)}</small></div>${deliveredAction}</div>`;
    }).join("");
    $("deliveryOrders").innerHTML=compact(deliveryOrders);
    $("deliveredOrders").innerHTML=compact(state.orders.filter(order=>order.status==="delivered").slice().reverse());
  }
  function openOrderDetails(id){
    const order=state.orders.find(entry=>String(entry.id)===String(id));
    if(!order){
      const candidate=state.candidates.find(entry=>String(entry.id)===String(id));if(!candidate)return;
      const detail=candidate.interpreted_order||{},address=detail.delivery_address||{};
      const location=[address.street,address.landmark,address.address_extra].filter(Boolean).map(escapeHtml).join(" · ");
      const items=(Array.isArray(detail.items)?detail.items:[]).map(item=>orderItemMarkup({...item,item_name:item.item_name||item.name,snapshot:item.snapshot||{options_text:item.options_text||item.modifications||""}},true)).join("");
      const notes=detail.notes?`<p class="expanded-order-note"><strong>Obs. do pedido:</strong> ${escapeHtml(detail.notes)}</p>`:"";
      const total=Number.isFinite(Number(detail.total))?`<strong class="expanded-order-total">${money(detail.total)}</strong>`:"";
      $("orderExpandedContent").innerHTML=`<div class="expanded-order-customer"><strong>${escapeHtml(detail.customer_known_as||detail.customer_name||"Pedido WhatsApp")}</strong>${location?`<small>${location}</small>`:""}</div><div class="expanded-order-items">${items}</div>${notes}${total}`;
      $("orderExpandedDialog").showModal();return;
    }
    const address=order.delivery_address||{};
    const location=[address.street,address.landmark,address.address_extra].filter(Boolean).map(escapeHtml).join(" · ");
    const items=(order.order_items||[]).map(item=>orderItemMarkup(item,true)).join("")+sellableTotalsMarkup(order);
    const notes=order.notes?`<p class="expanded-order-note"><strong>Obs. do pedido:</strong> ${escapeHtml(order.notes)}</p>`:"";
    $("orderExpandedContent").innerHTML=`<div class="expanded-order-customer"><strong>${escapeHtml(order.customer_known_as||order.customer_name||"")}</strong>${location?`<small>${location}</small>`:""}</div><div class="expanded-order-items">${items}</div>${notes}<strong class="expanded-order-total">${money(order.total)}</strong>`;
    $("orderExpandedDialog").showModal();
  }

  async function transitionOrder(id,status){if(status==="cancelled"&&!confirm("Recusar este pedido?"))return;if(status==="preparing"){const order=state.orders.find(entry=>String(entry.id)===String(id));if(order?.status==="received"){const confirmation=await db.rpc("transition_order",{target_order:id,next_status:"confirmed"});if(confirmation.error){toast(confirmation.error.message,true);return}}status="production"}const {data,error}=await db.rpc("transition_order",{target_order:id,next_status:status});if(error){toast(error.message,true);return}const updated=Array.isArray(data)?data[0]:data;state.orders=state.orders.map(order=>String(order.id)===String(id)?{...order,...(updated||{}),status:updated?.status||status}:order);renderOrders();await loadOrders()}

  async function loadCandidates(){state.candidates=(await query("whatsapp_order_candidates")).filter(c=>c.status==="pending").sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));renderCandidates()}
  function renderCandidates(){const homeBadge=$("candidateHomeBadge");homeBadge.textContent=state.candidates.length;homeBadge.hidden=!state.candidates.length;$("candidateList").innerHTML=state.candidates.map(c=>`<article class="candidate-card"><h3>Conversa ${escapeHtml(c.conversation_key)}</h3><div class="meta"><span class="pill">Confiança ${c.confidence==null?"—":Math.round(c.confidence*100)+"%"}</span><span>${new Date(c.created_at).toLocaleString("pt-BR")}</span></div><pre>${escapeHtml(JSON.stringify(c.interpreted_order,null,2))}</pre><div class="actions"><button class="button primary" data-candidate-confirm="${c.id}">Confirmar</button><button class="button" data-candidate-discard="${c.id}">Descartar</button></div></article>`).join("")||"<p>Nenhum candidato aguardando confirmação.</p>";renderOrders()}

  async function loadCatalog(){
    const packageComponentQuery=query("package_component","package_id,composition_id,sort_priority,free_allowance").catch(error=>{if(!/free_allowance|column/i.test(error.message||""))throw error;return query("package_component","package_id,composition_id,sort_priority")});
    const [items,categories,components,associations,packageComponents,itemComponentConfigs]=await Promise.all([
      query("items","id,name,description,price,stock,category_id,photo_url_1,photo_url_2,photo_url_3,sort_priority,stock_mode,is_active"),
      query("node_category","*"),
      query("composition","id,name,stock,price,is_active,max_quantity,tracks_stock"),
      query("item_composition_association","id,owner_id,composition_id,link_type,link_value,use_group_disjunction,group_disjunction_index"),
      packageComponentQuery,
      query("item_component_config","item_id,package_id,composition_id,default_quantity,free_allowance,max_quantity,consumption_per_unit,is_enabled")
    ]);
    try{state.itemPackages=await query("item_package","item_id,package_id,cart_pooling,sort_priority,shared_free_allowance")}
    catch(error){if(!/shared_free_allowance|column/i.test(error.message||""))throw error;state.itemPackages=(await query("item_package","item_id,package_id,cart_pooling,sort_priority")).map(row=>({...row,shared_free_allowance:0}));toast("Aplique a migration 20261010_10_component_group_modes_and_pooling.sql para configurar franquia compartilhada.",true)}
    try{state.packages=await query("ingredient_package","id,name,customer_name,kind,availability_rule,min_selections,max_selections,is_active,parent_id,sort_priority,franchise_mode,is_sellable")}
    catch(error){
      if(!/customer_name|availability_rule|parent_id|sort_priority|column/i.test(error.message||""))throw error;
      try{state.packages=(await query("ingredient_package","id,name,customer_name,kind,availability_rule,min_selections,max_selections,is_active,parent_id,sort_priority")).map((pack,index)=>({...pack,parent_id:pack.parent_id??null,sort_priority:pack.sort_priority??index}))}
      catch(legacyError){
        if(!/availability_rule|column/i.test(legacyError.message||""))throw legacyError;
        state.packages=(await query("ingredient_package","id,name,kind,min_selections,max_selections,is_active")).map((pack,index)=>({...pack,availability_rule:"optional_warn_only",parent_id:null,sort_priority:index}));
      }
      state.packages=state.packages.map(pack=>({...pack,customer_name:pack.customer_name||pack.name,franchise_mode:pack.franchise_mode||"none",is_sellable:pack.is_sellable===true}));
      toast("Aplique as migrations de nomes e modos dos grupos para editar todas as opções.",true);
    }
    try{state.packagePresentations=await query("package_component_presentation","package_id,composition_id,display_name,description,photo_url_1,photo_url_2,photo_url_3,is_active")}
    catch(error){if(!/package_component_presentation|schema cache|does not exist/i.test(error.message||""))throw error;state.packagePresentations=[]}
    state.items=items;state.categories=categories;state.components=components;state.associations=associations;state.packageComponents=packageComponents;state.itemComponentConfigs=itemComponentConfigs;
    const sort=(a,b)=>(a.sort_priority||0)-(b.sort_priority||0)||a.name.localeCompare(b.name);state.items.sort(sort);state.categories.sort(sort);state.components.sort((a,b)=>a.name.localeCompare(b.name));state.packages.sort(sort);renderStock();renderItems();renderCategories();renderComponents();renderOrders();populateCategoryControls();
    const route=location.hash.slice(1),visibleView=viewNames.includes(route)?route:state.view;
    const activeView=document.querySelector(".view.active")?.id;
    const layoutMatches=$("appView").classList.contains("orders-mode")===(visibleView==="orders")&&$("appView").classList.contains("home-mode")===(visibleView==="home");
    if(state.view!==visibleView||activeView!==`${visibleView}View`||!layoutMatches)switchView(visibleView)
  }

  function categoryPath(id){const names=[],seen=new Set();let current=state.categories.find(c=>c.id===id);while(current&&!seen.has(current.id)){seen.add(current.id);names.unshift(current.name);current=state.categories.find(c=>c.id===current.parent_id)}return names.join(" › ")||"Sem categoria"}
  function categoryOptions(excludeId=""){return state.categories.filter(c=>c.id!==excludeId).map(c=>`<option value="${escapeHtml(c.id)}">${escapeHtml(categoryPath(c.id))}</option>`).join("")}
  function populateCategoryControls(){const options=categoryOptions();$("itemCategoryFilter").innerHTML='<option value="all">Todas as categorias</option><option value="">Sem categoria</option>'+options;$("categoryComponentPackage").innerHTML='<option value="">Itens do cardápio</option>'+state.packages.filter(pack=>pack.is_sellable===true&&pack.kind==="scalable").map(pack=>`<option value="${escapeHtml(pack.id)}">${escapeHtml(pack.name)}</option>`).join("")}
  function childrenOf(parentId){return state.categories.filter(c=>(c.parent_id||null)===(parentId||null))}
  function itemsOf(categoryId){return state.items.filter(i=>(i.category_id||null)===(categoryId||null))}
  function itemMatches(item){const term=$("itemSearch").value.trim().toLocaleLowerCase(),filter=$("itemCategoryFilter").value;return(!term||`${item.name} ${item.description||""}`.toLocaleLowerCase().includes(term))&&(filter==="all"||(item.category_id||"")===filter)}
  function itemCompositionPrice(item){if(item.stock_mode!=="composition")return 0;const links=state.itemPackages.filter(link=>String(link.item_id)===String(item.id)),groups=links.map(link=>({link,pack:state.packages.find(pack=>String(pack.id)===String(link.package_id))})).filter(group=>group.pack&&group.pack.is_sellable!==true);if(!links.length)return state.associations.filter(association=>String(association.owner_id)===String(item.id)).reduce((sum,association)=>sum+Math.max(0,Number(association.link_value)||0)*Math.max(0,Number(state.components.find(component=>String(component.id)===String(association.composition_id))?.price)||0),0);return groups.reduce((sum,{link,pack})=>{const members=state.packageComponents.filter(member=>String(member.package_id)===String(pack.id)).map(member=>({member,component:state.components.find(component=>String(component.id)===String(member.composition_id)),config:state.itemComponentConfigs.find(config=>String(config.item_id)===String(item.id)&&String(config.package_id)===String(pack.id)&&String(config.composition_id)===String(member.composition_id))})).filter(entry=>entry.component&&entry.config?.is_enabled!==false);if(pack.franchise_mode==="shared"){const quantity=members.reduce((total,entry)=>total+Math.max(0,Number(entry.config?.default_quantity)||0),0),price=Math.max(0,Number(members[0]?.component.price)||0),allowance=Math.max(0,Number(link.shared_free_allowance)||0);return sum+Math.max(0,quantity-allowance)*price}return sum+members.reduce((total,{component,config})=>{const quantity=Math.max(0,Number(config?.default_quantity)||0),free=pack.franchise_mode==="per_component"?Math.max(0,Number(config?.free_allowance)||0):0;return total+Math.max(0,quantity-free)*Math.max(0,Number(component.price)||0)},0)},0)}
  function itemCard(item){const image=item.photo_url_1?`<img src="${escapeHtml(item.photo_url_1)}" alt="">`:'<div class="item-placeholder">AL</div>';const groupCount=state.itemPackages.filter(link=>link.item_id===item.id).length,composed=item.stock_mode==="composition",base=Math.max(0,Number(item.price)||0),composition=itemCompositionPrice(item),total=base+composition;return `<article class="menu-item-card ${composed?"composed-item-card":""} ${item.is_active===false?"inactive":""}">${image}<div class="menu-item-copy"><div class="menu-item-title"><strong>${escapeHtml(item.name)}</strong><span class="menu-item-price${composed?" has-breakdown":""}"><strong>${money(total)}</strong>${composed?`<small>${money(base)} base + ${money(composition)} composição</small>`:""}</span></div><p>${escapeHtml(item.description||"Sem descrição")}</p>${composed?`<div class="meta composed-item-meta"><span class="pill">Por composição</span><span>${groupCount} grupo(s)</span></div>`:""}<div class="meta item-status-meta"><span>${item.is_active===false?"Oculto":"Ativo"}</span></div></div><div class="item-card-actions"><button class="button photo-manage-button" data-item-photos="${escapeHtml(item.id)}" aria-label="Gerenciar fotos de ${escapeHtml(item.name)}" title="Gerenciar fotos">▧</button>${composed?`<button class="button" data-item-composition="${escapeHtml(item.id)}">Editar composição</button>`:""}<button class="button" data-item-edit="${escapeHtml(item.id)}">Editar</button></div></article>`}
  function categoryPackages(categoryId){const category=state.categories.find(entry=>String(entry.id)===String(categoryId)),pack=state.packages.find(entry=>String(entry.id)===String(category?.component_package_id||""));return pack?[pack]:[]}
  function componentPresentationCard(pack,component){const presentation=state.packagePresentations.find(row=>String(row.package_id)===String(pack.id)&&String(row.composition_id)===String(component.id)),image=presentation?.photo_url_1?`<img src="${escapeHtml(presentation.photo_url_1)}" alt="">`:'<div class="item-placeholder">AL</div>';return `<article class="menu-item-card component-presentation-card ${presentation?.is_active===false?"inactive":""}">${image}<div class="menu-item-copy"><div class="menu-item-title"><strong>${escapeHtml(presentation?.display_name||component.name)}</strong><strong>${money(component.price)}</strong></div><p>${escapeHtml(presentation?.description||"")}</p></div></article>`}
  function categoryEditor(category,level=0){const items=itemsOf(category.id).filter(itemMatches),packages=categoryPackages(category.id),children=childrenOf(category.id);const packageCards=packages.flatMap(pack=>state.packageComponents.filter(link=>String(link.package_id)===String(pack.id)).map(link=>state.components.find(component=>String(component.id)===String(link.composition_id))).filter(Boolean).map(component=>componentPresentationCard(pack,component))).join("");const visible=items.length||packageCards||children.some(c=>hasVisibleCategory(c));if(!visible&&($("itemSearch").value||$("itemCategoryFilter").value!=="all"))return"";return `<section class="menu-category" style="--depth:${level}"><header><div><span class="eyebrow">${escapeHtml(displayLabels[category.display_mode]||category.display_mode)}</span><h3>${escapeHtml(category.name)}</h3></div><div class="actions"><button class="button" data-category-add-item="${category.id}">+ Item</button><button class="button" data-category-add-composed="${category.id}">+ Item composto</button><button class="button" data-category-add-child="${category.id}">+ Subcategoria</button><button class="button" data-category-edit="${category.id}">Editar categoria</button></div></header><div class="menu-items">${items.map(itemCard).join("")}${packageCards}</div>${children.map(c=>categoryEditor(c,level+1)).join("")}</section>`}
  function hasVisibleCategory(category){return itemsOf(category.id).some(itemMatches)||categoryPackages(category.id).length>0||childrenOf(category.id).some(hasVisibleCategory)}
  function renderItems(){const roots=childrenOf(null);const orphanItems=itemsOf(null).filter(itemMatches);$("itemList").innerHTML=(orphanItems.length?`<section class="menu-category"><header><h3>Sem categoria</h3></header><div class="menu-items">${orphanItems.map(itemCard).join("")}</div></section>`:"")+roots.map(c=>categoryEditor(c)).join("")||"<p>Nenhum item corresponde aos filtros.</p>"}

  function categoryTreeRows(parentId=null,level=0){return childrenOf(parentId).map(c=>{const packageId=c.component_package_id,componentCount=packageId?state.packageComponents.filter(row=>String(row.package_id)===String(packageId)).length:0;return `<article class="tree-row" style="--depth:${level}"><div><strong>${escapeHtml(c.name)}</strong><small>${escapeHtml(c.id)} · ${escapeHtml(displayLabels[c.display_mode]||c.display_mode)} · ${packageId?`${componentCount} representação(ões) de componente`: `${itemsOf(c.id).length} item(ns)`}</small></div><div class="actions">${packageId?`<button class="button" data-package-presentation="${escapeHtml(packageId)}">Editar representações</button>`:`<button class="button" data-category-add-item="${c.id}">+ Item</button><button class="button" data-category-add-composed="${c.id}">+ Item composto</button>`}<button class="button" data-category-add-child="${c.id}">+ Subcategoria</button><button class="button" data-category-edit="${c.id}">Editar</button></div></article>${categoryTreeRows(c.id,level+1)}`}).join("")}
  function renderCategories(){$("categoryTree").innerHTML=categoryTreeRows()||"<p>Nenhuma categoria cadastrada.</p>"}
  function packagePresentationRows(packageId){return state.packageComponents.filter(row=>String(row.package_id)===String(packageId)).sort((a,b)=>(a.sort_priority||0)-(b.sort_priority||0)).map(link=>{const component=state.components.find(entry=>String(entry.id)===String(link.composition_id));if(!component)return"";const presentation=state.packagePresentations.find(entry=>String(entry.package_id)===String(packageId)&&String(entry.composition_id)===String(component.id));return `<article class="component-presentation-edit-row" data-presentation-row data-composition-id="${escapeHtml(component.id)}"><div class="component-presentation-source"><strong>${escapeHtml(component.name)}</strong><small>${money(component.price)}</small></div><label>Nome no cardápio<input data-presentation-name maxlength="100" value="${escapeHtml(presentation?.display_name||"")}" placeholder="${escapeHtml(component.name)}"></label><label>Descrição<textarea data-presentation-description maxlength="500" rows="2">${escapeHtml(presentation?.description||"")}</textarea></label><label>Foto<input data-presentation-photo type="url" value="${escapeHtml(presentation?.photo_url_1||"")}" placeholder="https://..."><input data-presentation-file type="file" accept="image/*"></label></article>`}).join("")||"<p>Este grupo ainda não possui componentes.</p>"}
  function openPackagePresentations(packageId){const pack=state.packages.find(entry=>String(entry.id)===String(packageId));if(!pack)return;state.activePresentationPackageId=String(pack.id);$("presentationDialogTitle").textContent=`Representações · ${pack.customer_name||pack.name}`;$("packagePresentationList").innerHTML=packagePresentationRows(pack.id);$("packagePresentationDialog").showModal()}
  async function savePackagePresentations(event){event.preventDefault();const packageId=state.activePresentationPackageId;if(!packageId)return;const button=$("savePackagePresentations");button.disabled=true;try{for(const row of $("packagePresentationList").querySelectorAll("[data-presentation-row]")){const compositionId=row.dataset.compositionId,file=row.querySelector("[data-presentation-file]").files?.[0];let photoUrl=row.querySelector("[data-presentation-photo]").value.trim()||null;if(file){if(!file.type.startsWith("image/"))throw new Error(`O arquivo de ${row.querySelector("[data-presentation-name]").placeholder} não é uma imagem.`);const extension=(file.name.split(".").pop()||"jpg").toLowerCase().replace(/[^a-z0-9]/g,"")||"jpg",path=`representations/${packageId}/${compositionId}/photo.${extension}`;const {error}=await db.storage.from("item-photos").upload(path,file,{upsert:true,contentType:file.type,cacheControl:"3600"});if(error)throw error;photoUrl=db.storage.from("item-photos").getPublicUrl(path).data.publicUrl}const payload={package_id:packageId,composition_id:compositionId,display_name:row.querySelector("[data-presentation-name]").value.trim()||null,description:row.querySelector("[data-presentation-description]").value.trim(),photo_url_1:photoUrl};const {error}=await db.from("package_component_presentation").upsert(payload,{onConflict:"package_id,composition_id"});if(error)throw error}$("packagePresentationDialog").close();state.activePresentationPackageId=null;toast("Representações atualizadas.");await loadCatalog()}catch(error){toast(/package_component_presentation|schema cache|does not exist/i.test(error.message||"")?"Aplique a migration 20261010_13_component_package_showcase.sql antes de salvar as representações.":error.message,true)}finally{button.disabled=false}}
  function componentSummaryRow(component){return `<article class="component-group-row"><div><strong>${escapeHtml(component.name)}</strong><small>${component.tracks_stock?`Saldo ${component.stock}`:"Sem controle de estoque"} · ${component.is_active===false?"Desativado":"Ativo"}</small></div><strong>${money(component.price)}</strong></article>`}
  function packageMatches(pack,term){const own=pack.name.toLocaleLowerCase().includes(term),members=state.packageComponents.filter(row=>row.package_id===pack.id).some(row=>state.components.find(c=>String(c.id)===String(row.composition_id))?.name.toLocaleLowerCase().includes(term));return own||members}
  function packageSubtreeMatches(packId,term){return state.packages.filter(entry=>String(entry.parent_id||"")===String(packId)).some(child=>packageMatches(child,term)||packageSubtreeMatches(child.id,term))}
  function packageTreeRows(parentId=null,level=0,term=""){
    return state.packages.filter(pack=>(pack.parent_id||null)===(parentId||null)).filter(pack=>!term||packageMatches(pack,term)||packageSubtreeMatches(pack.id,term)).map(pack=>{
      const members=state.packageComponents.filter(row=>row.package_id===pack.id).sort((a,b)=>(a.sort_priority||0)-(b.sort_priority||0)).map(row=>state.components.find(component=>String(component.id)===String(row.composition_id))).filter(Boolean);
      const children=packageTreeRows(pack.id,level+1,term),products=state.itemPackages.filter(row=>row.package_id===pack.id).length;
      const visibleMembers=members.filter(component=>!term||component.name.toLocaleLowerCase().includes(term)||pack.name.toLocaleLowerCase().includes(term));
      return `<section class="component-group-node" style="--group-depth:${Math.min(level,5)}"><header class="component-group-heading"><div><span class="component-group-index">${Number(pack.sort_priority)||0}</span><strong>${escapeHtml(pack.name)}</strong><span class="pill">${escapeHtml(packageKindLabels[pack.kind]||pack.kind)}</span><span class="pill">${escapeHtml(packageAvailabilityLabels[pack.availability_rule]||"Regra não definida")}</span></div><div class="actions"><button class="button" data-package-manage="${escapeHtml(pack.id)}">Gerenciar este grupo</button>${pack.is_sellable?`<button class="button" data-package-presentation="${escapeHtml(pack.id)}">Editar representações</button>`:""}<button class="button" data-package-edit="${escapeHtml(pack.id)}">Editar grupo</button><button class="button danger-button" data-package-delete="${escapeHtml(pack.id)}">Excluir grupo</button></div></header><div class="component-group-meta"><span>Público: ${escapeHtml(pack.customer_name||pack.name)}</span><span>${visibleMembers.length} componente(s)</span><span>${products} item(ns)</span><span>Franquia: ${escapeHtml(pack.franchise_mode||"none")}</span>${pack.is_sellable?"<span>Vendável</span>":""}${pack.is_active===false?"<span>Desativado</span>":""}</div><div class="component-group-members">${visibleMembers.map(componentSummaryRow).join("")||"<small>Sem componentes</small>"}</div>${children}</section>`;
    }).join("")
  }
  function renderComponents(){
    const term=$("componentSearch").value.trim().toLocaleLowerCase(),groups=packageTreeRows(null,0,term);
    $("componentList").innerHTML=groups||"<p>Nenhum grupo cadastrado.</p>";
  }
  function itemPackageRows(itemId=""){
    const attached=new Set(state.itemPackages.filter(row=>String(row.item_id)===String(itemId)).map(row=>String(row.package_id)));
    const groups=state.packages.filter(pack=>pack.is_active!==false).sort((a,b)=>(Number(a.sort_priority)||0)-(Number(b.sort_priority)||0)||String(packagePath(a.id)).localeCompare(String(packagePath(b.id))));
    return groups.map(pack=>{const isAttached=attached.has(String(pack.id)),franchise=pack.franchise_mode==="per_component"?"Franquia individual":pack.franchise_mode==="shared"?"Franquia somatória":"Sem franquia";return `<article class="item-package-link-row ${isAttached?"is-associated":""}" data-item-package-link="${escapeHtml(pack.id)}"><label class="item-package-check"><input type="checkbox" data-item-package-toggle="${escapeHtml(pack.id)}" ${isAttached?"checked":""}><span><strong>${escapeHtml(pack.name)}</strong><small>${escapeHtml(packagePath(pack.id))} · ${escapeHtml(pack.customer_name||pack.name)} · ${escapeHtml(packageKindLabels[pack.kind]||pack.kind)} · ${franchise}</small></span></label>${isAttached?`<button type="button" class="button" data-item-package-manage="${escapeHtml(pack.id)}">Gerenciar</button>`:""}</article>`}).join("")||"<p>Nenhum grupo disponível.</p>";
  }
  function renderItemComposition(itemId=$("compositionItemId").value){$("itemPackageList").innerHTML=itemPackageRows(itemId)}
  function openItemComposition(itemId){const item=state.items.find(entry=>String(entry.id)===String(itemId));if(!item||item.stock_mode!=="composition")return;$("compositionItemId").value=item.id;$("compositionItemTitle").textContent=`Editar composição · ${item.name}`;renderItemComposition(item.id);$("itemCompositionDialog").showModal()}
  async function addItemPackage(packageId){const itemId=$("compositionItemId").value,pack=state.packages.find(entry=>String(entry.id)===String(packageId));if(!itemId||!pack)return false;const {error}=await db.from("item_package").insert({item_id:itemId,package_id:packageId,cart_pooling:false,sort_priority:Number(pack.sort_priority)||0,shared_free_allowance:0});if(error){toast(error.message,true);return false}await loadCatalog();renderItemComposition(itemId);toast("Grupo associado.");return true}
  async function removeItemPackage(packageId){const itemId=$("compositionItemId").value;if(!itemId)return false;const {error:configError}=await db.from("item_component_config").delete().eq("item_id",itemId).eq("package_id",packageId);if(configError){toast(configError.message,true);return false}const {error}=await db.from("item_package").delete().eq("item_id",itemId).eq("package_id",packageId);if(error){toast(error.message,true);return false}await loadCatalog();renderItemComposition(itemId);toast("Grupo removido do item.");return true}
  function openItemPackageManager(packageId){const itemId=$("compositionItemId").value,item=state.items.find(entry=>String(entry.id)===String(itemId)),pack=state.packages.find(entry=>String(entry.id)===String(packageId));if(!item||!pack)return;const link=state.itemPackages.find(row=>String(row.item_id)===String(itemId)&&String(row.package_id)===String(packageId));$("managedItemPackageId").value=packageId;$("itemGroupManagerTitle").textContent=`${pack.name} · ${item.name}`;$("itemGroupManagerSummary").innerHTML=`<span>${escapeHtml(pack.customer_name||pack.name)}</span><span>${escapeHtml(pack.franchise_mode==="shared"?"Franquia somatória":pack.franchise_mode==="per_component"?"Franquia individual":"Sem franquia")}</span>${pack.franchise_mode==="shared"?`<label>Franquia gratuita para este item<input type="number" min="0" step="1" data-association-shared-allowance value="${Math.max(0,Number(link?.shared_free_allowance)||0)}"></label>`:""}`;const quantityLimit=pack.kind==="adjustable"?2:["complementary","single_required","decay"].includes(pack.kind)?1:Infinity;$("itemGroupManagerList").innerHTML=state.packageComponents.filter(row=>String(row.package_id)===String(packageId)).sort((a,b)=>(a.sort_priority||0)-(b.sort_priority||0)).map(member=>{const component=state.components.find(entry=>String(entry.id)===String(member.composition_id));if(!component)return"";const config=state.itemComponentConfigs.find(entry=>String(entry.item_id)===String(itemId)&&String(entry.package_id)===String(packageId)&&String(entry.composition_id)===String(component.id)),max=Math.min(quantityLimit,Number(config?.max_quantity??component.max_quantity??4)),free=pack.franchise_mode==="per_component"?Number(config?.free_allowance??member.free_allowance??0):0;return `<article class="item-group-config-row" data-item-group-config="${escapeHtml(component.id)}" data-config-max="${Number.isFinite(max)?max:""}" data-config-enabled="${config?.is_enabled===false?"false":"true"}" data-config-consumption="${Number(config?.consumption_per_unit??1)}"><strong>${escapeHtml(component.name)}</strong><label>Padrão<input type="number" min="0" max="${Number.isFinite(max)?max:""}" step="1" data-config-value="default_quantity" value="${Math.min(max,Number(config?.default_quantity)||0)}"></label>${pack.franchise_mode==="per_component"?`<label>Franquia grátis<input type="number" min="0" max="${Number.isFinite(max)?max:""}" step="1" data-config-value="free_allowance" value="${Math.min(max,free)}"></label>`:""}</article>`}).join("")||"<p>Este grupo não tem componentes cadastrados.</p>";$("itemGroupManagerDialog").showModal()}
  async function saveItemPackageManager(event){event.preventDefault();const packageId=$("managedItemPackageId").value,itemId=$("compositionItemId").value,pack=state.packages.find(entry=>String(entry.id)===String(packageId)),link=state.itemPackages.find(row=>String(row.item_id)===String(itemId)&&String(row.package_id)===String(packageId));if(!pack||!link)return;const sharedAllowance=Number($("itemGroupManagerSummary").querySelector("[data-association-shared-allowance]")?.value||0);if(!Number.isInteger(sharedAllowance)||sharedAllowance<0){toast("A franquia deve ser um inteiro não negativo.",true);return}const configs=[];for(const row of $("itemGroupManagerList").querySelectorAll("[data-item-group-config]")){const values={};for(const input of row.querySelectorAll("[data-config-value]")){const value=Number(input.value);if(!Number.isInteger(value)||value<0){toast("Use quantidades inteiras não negativas.",true);return}values[input.dataset.configValue]=value}const max=Number(row.dataset.configMax);if(values.default_quantity>max||(pack.franchise_mode==="per_component"&&values.free_allowance>max)){toast("Padrão e franquia não podem exceder o limite do componente.",true);return}configs.push({item_id:itemId,package_id:packageId,composition_id:row.dataset.itemGroupConfig,is_enabled:row.dataset.configEnabled!=="false",default_quantity:values.default_quantity,free_allowance:pack.franchise_mode==="per_component"?values.free_allowance:0,max_quantity:max,consumption_per_unit:Number(row.dataset.configConsumption)||1})}const activeDefaults=configs.filter(entry=>entry.is_enabled&&entry.default_quantity>0);if(pack.availability_rule==="one_available_with_priority_fallback"&&(activeDefaults.length!==1||activeDefaults[0].default_quantity!==1)){toast(`O grupo “${pack.name}” precisa ter uma opção padrão na quantidade 1.`,true);return}if(["single_required","decay"].includes(pack.kind)&&(activeDefaults.length!==1||activeDefaults[0].default_quantity!==1)){toast(`O grupo “${pack.name}” precisa ter exatamente uma escolha padrão.`,true);return}if(pack.franchise_mode==="shared"){const {error:linkError}=await db.from("item_package").update({shared_free_allowance:sharedAllowance}).eq("item_id",itemId).eq("package_id",packageId);if(linkError){toast(linkError.message,true);return}}if(configs.length){const {error}=await db.from("item_component_config").upsert(configs,{onConflict:"item_id,package_id,composition_id"});if(error){toast(error.message,true);return}}$("itemGroupManagerDialog").close();await loadCatalog();renderItemComposition(itemId);toast("Associação atualizada.")}
  function packageParentOptions(pack){
    const descendants=new Set();const collect=id=>state.packages.filter(entry=>entry.parent_id===id&&!descendants.has(entry.id)).forEach(entry=>{descendants.add(entry.id);collect(entry.id)});if(pack)collect(pack.id);
    return '<option value="">Raiz</option>'+state.packages.filter(entry=>entry.id!==pack?.id&&!descendants.has(entry.id)).map(entry=>`<option value="${escapeHtml(entry.id)}">${escapeHtml(packagePath(entry.id))}</option>`).join("");
  }
  function packagePath(id){const path=[],seen=new Set();let current=state.packages.find(entry=>String(entry.id)===String(id));while(current&&!seen.has(current.id)){seen.add(current.id);path.unshift(current.name);current=state.packages.find(entry=>String(entry.id)===String(current.parent_id))}return path.join(" › ")}
  function openPackage(id="",parentId=""){const pack=state.packages.find(p=>p.id===id);$("packageForm").reset();$("packageId").value=pack?.id||"";$("packageDialogTitle").textContent=pack?`Editar grupo: ${pack.name}`:"Novo grupo";$("packageName").value=pack?.name||"";$("packageCustomerName").value=pack?.customer_name||pack?.name||"";$("packageKind").value=pack?.kind||"adjustable";$("packageFranchiseMode").value=pack?.franchise_mode||"none";$("packageSellable").checked=pack?.is_sellable===true;$("packageAvailabilityRule").value=pack?.availability_rule||"optional_warn_only";$("packageMin").value=pack?.min_selections??0;$("packageRequiresSelection").checked=Number(pack?.min_selections||0)>0;$("packageMax").value=pack?.max_selections??"";$("packageParent").innerHTML=packageParentOptions(pack);$("packageParent").value=pack?.parent_id||parentId||"";$("packagePriority").value=pack?.sort_priority??0;$("packageActive").checked=pack?.is_active!==false;$("deletePackage").hidden=!pack;$("packageDialog").showModal()}
  async function savePackage(event){
    event.preventDefault();
    const id=$("packageId").value,name=$("packageName").value.trim(),customerName=$("packageCustomerName").value.trim(),minSelections=Math.trunc(Number($("packageMin").value)||0),maxRaw=$("packageMax").value.trim(),maxSelections=maxRaw===""?null:Math.trunc(Number(maxRaw));
    if(!name||!customerName){toast("Preencha o nome interno e o nome que aparece no cardápio.",true);return}
    if(maxSelections!==null&&maxSelections<minSelections){toast("O máximo deve ser igual ou maior que o mínimo.",true);return}
    const priority=Math.trunc(Number($("packagePriority").value));if(!Number.isInteger(priority)||priority<0){toast("A prioridade deve ser um número inteiro não negativo.",true);return}
    const isSellable=$("packageSellable").checked,franchiseMode=$("packageFranchiseMode").value;
    if(isSellable&&$("packageKind").value!=="scalable"){toast("Somente grupos escaláveis podem ser vendidos como escolha própria.",true);return}
    if(franchiseMode!=="none"&&$("packageKind").value!=="scalable"){toast("Franquia pode ser configurada apenas em grupos escaláveis.",true);return}
    const kind=$("packageKind").value,isDecay=kind==="decay";
    const payload={name,customer_name:customerName,kind,franchise_mode:franchiseMode,is_sellable:isSellable,availability_rule:isSellable?"optional_warn_only":isDecay?"one_available_with_priority_fallback":$("packageAvailabilityRule").value,min_selections:isSellable?0:isDecay?1:minSelections,max_selections:isSellable?null:isDecay?1:maxSelections,is_active:$("packageActive").checked,parent_id:$("packageParent").value||null,sort_priority:priority};
    let packageId=id;
    if(id){const {error}=await db.from("ingredient_package").update(payload).eq("id",id);if(error){toast(/customer_name|column|franchise_mode|is_sellable/i.test(error.message||"")?"Aplique as migrations 20261010_09_component_group_customer_name.sql e 20261010_10_component_group_modes_and_pooling.sql antes de salvar os grupos.":error.message,true);return}}
    else{const {data,error}=await db.from("ingredient_package").insert(payload).select("id").single();if(error){toast(/customer_name|column|franchise_mode|is_sellable/i.test(error.message||"")?"Aplique as migrations 20261010_09_component_group_customer_name.sql e 20261010_10_component_group_modes_and_pooling.sql antes de salvar os grupos.":error.message,true);return}packageId=data.id}
    $("packageDialog").close();toast(id?"Grupo atualizado.":"Grupo criado.");await loadCatalog()
  }
  function openGroupComponents(packageId){
    const pack=state.packages.find(entry=>String(entry.id)===String(packageId));if(!pack)return;
    state.activePackageManagerId=String(pack.id);
    state.packageComponentDraft=new Map(state.packageComponents.filter(row=>String(row.package_id)===String(pack.id)).map(row=>[String(row.composition_id),Math.max(0,Math.trunc(Number(row.sort_priority)||0))]));
    $("groupComponentsPackageId").value=pack.id;$("groupComponentsTitle").textContent=`Gerenciar este grupo: ${pack.name}`;
    renderGroupComponentsManager();$("groupComponentsDialog").showModal()
  }
  function renderGroupComponentsManager(){
    const draft=state.packageComponentDraft,pack=state.packages.find(entry=>String(entry.id)===String(state.activePackageManagerId));
    const rows=[...draft.entries()].map(([componentId,priority])=>{
      const component=state.components.find(entry=>String(entry.id)===componentId);if(!component)return"";
      const link=state.packageComponents.find(row=>String(row.package_id)===String(state.activePackageManagerId)&&String(row.composition_id)===componentId);
      return `<article class="group-component-row" data-group-component-row data-component-id="${escapeHtml(componentId)}"><input aria-label="Nome" data-component-name value="${escapeHtml(component.name)}"><input aria-label="Preço" type="number" min="0" step="0.01" data-component-price value="${Number(component.price)||0}"><input aria-label="Franquia grátis" title="Franquia grátis" type="number" min="0" step="1" data-component-allowance value="${Math.max(0,Number(link?.free_allowance)||0)}" ${pack?.franchise_mode==="per_component"?"":"disabled"}><input aria-label="Limite de adição" type="number" min="0" step="1" data-component-max value="${Math.max(0,Number(component.max_quantity)||0)}"><input aria-label="Prioridade" type="number" min="0" step="1" data-group-component-priority value="${priority}"><button type="button" class="button danger-button" data-group-component-remove="${escapeHtml(componentId)}" aria-label="Remover do grupo">×</button></article>`;
    }).join("");
    $("groupComponentsList").innerHTML=rows;
  }
  function addGroupComponent(){
    const pack=state.packages.find(entry=>String(entry.id)===String(state.activePackageManagerId));
    const row=document.createElement("article");row.className="group-component-row";row.dataset.groupComponentRow="";row.innerHTML=`<input aria-label="Nome" data-component-name placeholder="Nome do componente"><input aria-label="Preço" type="number" min="0" step="0.01" data-component-price value="0"><input aria-label="Franquia grátis" title="Franquia grátis" type="number" min="0" step="1" data-component-allowance value="0" ${pack?.franchise_mode==="per_component"?"":"disabled"}><input aria-label="Limite de adição" type="number" min="0" step="1" data-component-max value="4"><input aria-label="Prioridade" type="number" min="0" step="1" data-group-component-priority value="${Math.max(-1,...state.packageComponentDraft.values())+1}"><button type="button" class="button danger-button" data-new-row-remove aria-label="Remover linha">×</button>`;
    $("groupComponentsList").append(row);row.querySelector("[data-component-name]").focus()
  }
  async function saveGroupComponents(event){
    event.preventDefault();
    const packageId=$("groupComponentsPackageId").value,pack=state.packages.find(entry=>String(entry.id)===String(packageId));if(!pack)return;
    if(pack.franchise_mode==="per_component"){const {error}=await db.from("package_component").select("free_allowance").limit(1);if(error){toast("Aplique a migration 20261010_12_package_component_defaults.sql antes de configurar franquia por componente.",true);return}}
    const enteredPrices=[...$("groupComponentsList").querySelectorAll("[data-component-price]")].map(input=>Number(input.value));if(pack.franchise_mode==="shared"&&enteredPrices.some(price=>!Number.isFinite(price)||price!==enteredPrices[0])){toast("Franquia compartilhada exige o mesmo preço em todos os componentes do grupo.",true);return}
    const rows=[],seenNames=new Set();
    for(const row of $("groupComponentsList").querySelectorAll("[data-group-component-row]")){
      const name=row.querySelector("[data-component-name]").value.trim(),price=Number(row.querySelector("[data-component-price]").value),max_quantity=Math.trunc(Number(row.querySelector("[data-component-max]").value)),free_allowance=Math.trunc(Number(row.querySelector("[data-component-allowance]").value)||0),sort_priority=Math.trunc(Number(row.querySelector("[data-group-component-priority]").value));
      if(!name||!Number.isFinite(price)||price<0||![max_quantity,free_allowance,sort_priority].every(Number.isInteger)||max_quantity<0||free_allowance<0||sort_priority<0){toast("Preencha cada linha com nome, preço e quantidades inteiras não negativas.",true);return}
      const normalizedName=name.toLocaleLowerCase();if(seenNames.has(normalizedName)){toast("Cada componente deve aparecer uma única vez neste grupo.",true);return}seenNames.add(normalizedName);
      let composition_id=row.dataset.componentId;
      if(composition_id){const {error}=await db.from("composition").update({name,price,max_quantity}).eq("id",composition_id);if(error){toast(error.message,true);return}}
      else{const {data,error}=await db.from("composition").insert({name,price,max_quantity,stock:0,tracks_stock:true,is_active:true}).select("id").single();if(error){toast(error.message,true);return}composition_id=String(data.id)}
      rows.push({package_id:packageId,composition_id,sort_priority,...(pack.franchise_mode==="per_component"?{free_allowance}:{})});
    }
    if(pack.kind==="decay"&&!rows.length){toast("Decaimento precisa de ao menos uma opção ordenada no grupo.",true);return}
    const selected=new Set(rows.map(row=>String(row.composition_id)));
    const existing=state.packageComponents.filter(row=>String(row.package_id)===String(packageId)),remove=existing.filter(row=>!selected.has(String(row.composition_id)));
    for(const row of remove){const {error}=await db.from("package_component").delete().eq("package_id",packageId).eq("composition_id",row.composition_id);if(error){toast(`Grupo mantido, mas não foi possível remover um componente: ${error.message}`,true);await loadCatalog();return}}
    if(rows.length){const {error}=await db.from("package_component").upsert(rows,{onConflict:"package_id,composition_id"});if(error){toast(/free_allowance|column/i.test(error.message||"")?"Aplique a migration 20261010_12_package_component_defaults.sql para salvar a franquia padrão do grupo.":`Não foi possível salvar os componentes do grupo: ${error.message}`,true);await loadCatalog();return}}
    $("groupComponentsDialog").close();state.activePackageManagerId=null;toast("Componentes do grupo atualizados.");await loadCatalog()
  }
  async function deletePackage(id=$("packageId").value){
    if(!id)return;
    const pack=state.packages.find(entry=>String(entry.id)===String(id));if(!pack)return;
    const itemCount=state.itemPackages.filter(row=>String(row.package_id)===String(id)).length;
    const childCount=state.packages.filter(row=>String(row.parent_id||"")===String(id)).length;
    const confirmation=prompt(`Excluir o grupo “${pack.name}”${itemCount?`? Ele está associado a ${itemCount} item(ns), e essas associações também serão removidas`:"?"}${childCount?`; ${childCount} grupo(s) filho(s) permanecerão como grupos raiz`:""}. Os itens e categorias serão mantidos. Digite SIM para confirmar.`);
    if(confirmation?.trim().toLocaleLowerCase()!=="sim")return;
    const {error}=await db.from("ingredient_package").delete().eq("id",id);if(error){toast(error.message,true);return}
    $("packageDialog").close();toast(`Grupo “${pack.name}” excluído.`);await loadCatalog()
  }

  function inventoryKey(kind,id){return `${kind}:${id}`}
  function inventoryBase(x){const hidden=x.kind==="composition"?x.is_active===false:Number(x.stock||0)<0,stock=Math.max(0,Number(x.stock||0));return{kind:x.kind,id:String(x.id),hidden,finished:!hidden&&stock===0,stock}}
  function inventoryValue(x){return state.inventoryDrafts.get(inventoryKey(x.kind,x.id))||inventoryBase(x)}
  function inventoryState(x){const value=inventoryValue(x);return value.hidden?"hidden":value.finished?"finished":"visible"}
  function groupedComponents(){const linked=new Set(state.packageComponents.map(row=>String(row.composition_id)));return state.components.filter(component=>linked.has(String(component.id)))}
  function stockRows(){const term=$("stockSearch").value.trim().toLocaleLowerCase(),kind=document.querySelector("[data-stock-kind].active")?.dataset.stockKind||"all",status=$("stockState").value;return[...state.items.map(x=>({...x,kind:"item"})),...groupedComponents().map(x=>({...x,kind:"composition"}))].filter(x=>(kind==="all"||x.kind===kind)&&(status==="all"||inventoryState(x)===status)&&`${x.name} ${x.id}`.toLocaleLowerCase().includes(term))}
  function inventoryGroupName(x){return x.kind==="composition"?"Componentes":categoryPath(x.category_id)}
  function inventoryRow(x){const value=inventoryValue(x),changed=state.inventoryDrafts.has(inventoryKey(x.kind,x.id)),photo=x.kind==="item"&&x.photo_url_1?`<img class="inventory-photo" src="${escapeHtml(x.photo_url_1)}" alt="">`:'<div class="inventory-photo item-placeholder">AL</div>';return `<article class="inventory-row ${value.hidden?"is-hidden":""} ${changed?"is-changed":""}" data-inventory-kind="${x.kind}" data-inventory-id="${escapeHtml(x.id)}">${photo}<div class="inventory-name"><strong>${escapeHtml(x.name)}</strong><small>${escapeHtml(x.id)} · ${x.kind==="item"?(x.stock_mode==="composition"?"item por composição":"item direto"):"componente"}</small></div><label class="switch inventory-hidden"><input class="inventory-hidden-input" type="checkbox" ${value.hidden?"checked":""}><span class="switch-track"></span><span class="switch-text">${value.hidden?"Oculto":"Visível"}</span></label><label class="switch inventory-finished"><input class="inventory-finished-input" type="checkbox" ${value.finished?"checked":""}><span class="switch-track"></span><span class="switch-text">${value.finished?"Finalizado":"Disponível"}</span></label><div class="stock-steps"><button type="button" data-stock-delta="-10">-10</button><button type="button" data-stock-delta="-1">−</button><input class="inventory-stock-input" type="number" min="0" step="1" value="${value.stock}" aria-label="Estoque de ${escapeHtml(x.name)}"><button type="button" data-stock-delta="1">+</button><button type="button" data-stock-delta="10">+10</button></div></article>`}
  function updateInventorySaveButton(){const count=state.inventoryDrafts.size;$("inventoryChangeCount").textContent=`(${count})`;$("saveInventory").disabled=count===0}
  function renderStock(){const all=[...state.items.map(x=>({...x,kind:"item"})),...groupedComponents().map(x=>({...x,kind:"composition"}))],rows=stockRows(),groups=new Map;for(const x of rows){const group=inventoryGroupName(x);if(!groups.has(group))groups.set(group,[]);groups.get(group).push(x)}$("stockTotal").textContent=`Itens: ${all.length}`;$("stockVisible").textContent=`Visíveis: ${all.filter(x=>inventoryState(x)==="visible").length}`;$("stockFinished").textContent=`Finalizados: ${all.filter(x=>inventoryState(x)==="finished").length}`;$("stockHidden").textContent=`Ocultos: ${all.filter(x=>inventoryState(x)==="hidden").length}`;$("stockList").innerHTML=[...groups].map(([name,entries])=>`<section class="inventory-group"><h3>${escapeHtml(name)} (${entries.length})</h3>${entries.map(inventoryRow).join("")}</section>`).join("")||'<section class="inventory-group"><h3>Nenhum registro encontrado.</h3></section>';updateInventorySaveButton()}
  function markInventoryChanged(row){const kind=row.dataset.inventoryKind,id=row.dataset.inventoryId,entry=(kind==="item"?state.items:state.components).find(x=>String(x.id)===id),base=inventoryBase({...entry,kind}),draft={kind,id,hidden:row.querySelector(".inventory-hidden-input").checked,finished:row.querySelector(".inventory-finished-input").checked,stock:Math.max(0,Math.trunc(Number(row.querySelector(".inventory-stock-input").value)||0))},changed=draft.hidden!==base.hidden||draft.finished!==base.finished||draft.stock!==base.stock,key=inventoryKey(kind,id);if(changed)state.inventoryDrafts.set(key,draft);else state.inventoryDrafts.delete(key);row.classList.toggle("is-hidden",draft.hidden);row.classList.toggle("is-changed",changed);row.querySelector(".inventory-hidden .switch-text").textContent=draft.hidden?"Oculto":"Visível";row.querySelector(".inventory-finished .switch-text").textContent=draft.finished?"Finalizado":"Disponível";updateInventorySaveButton()}
  async function saveInventoryChanges(){const button=$("saveInventory"),drafts=[...state.inventoryDrafts.entries()];if(!drafts.length)return;button.disabled=true;button.textContent="Salvando...";let failed=0;for(const [key,draft] of drafts){let stock=draft.finished?0:draft.stock;if(draft.kind==="item"&&draft.hidden)stock=-1;const table=draft.kind==="item"?"items":"composition",payload=draft.kind==="item"?{stock}:{stock,is_active:!draft.hidden};const {error}=await db.from(table).update(payload).eq("id",draft.id);if(error)failed+=1;else state.inventoryDrafts.delete(key)}button.innerHTML='Salvar alterações <span id="inventoryChangeCount"></span>';if(failed)toast(`${failed} alteração(ões) não foram salvas.`,true);else toast(`${drafts.length} alteração(ões) salvas.`);await loadCatalog()}
  function openStock(kind,id){const entry=(kind==="item"?state.items:state.components).find(x=>String(x.id)===id);if(!entry)return;$("stockTargetKind").value=kind;$("stockTargetId").value=id;$("stockDialogTitle").textContent=entry.name;$("stockAmount").value="";$("stockReason").value="";$("stockPreview").dataset.current=entry.stock;updatePreview();$("stockDialog").showModal()}
  function updatePreview(){const current=Number($("stockPreview").dataset.current||0),amount=Number($("stockAmount").value||0);const result=$("stockOperation").value==="set"?amount:current-amount;$("stockPreview").textContent=`Saldo atual: ${current} → novo saldo: ${result}`;$("confirmStock").disabled=result<0||!Number.isInteger(amount)}
  async function saveStock(event){event.preventDefault();const payload={target_kind:$("stockTargetKind").value,target_id:$("stockTargetId").value,operation:$("stockOperation").value,amount:Number($("stockAmount").value),reason:$("stockReason").value||null};const {error}=await db.rpc("adjust_inventory",payload);if(error){toast(error.message,true);return}$("stockDialog").close();toast("Estoque atualizado.");await loadCatalog()}

  function openItem(id="",categoryId="",kind="direct"){
    const item=state.items.find(x=>String(x.id)===String(id));
    $("itemForm").reset();$("itemId").value=item?.id||"";$("itemKind").value=item?.stock_mode||kind;$("itemCategory").value=item?.category_id||categoryId||"";$("itemDialogTitle").textContent=item?`Editar ${item.name}`:kind==="composition"?"Novo item composto":"Novo item";
    $("itemName").value=item?.name||"";$("itemDescription").value=item?.description||"";$("itemPrice").value=item?.price??0;$("itemPriceLabel").textContent=$("itemKind").value==="composition"?"Preço base":"Preço";$("itemActive").checked=item?.is_active!==false;
    $("deleteItem").hidden=!item;$("manageItemPhotos").hidden=!item;$("editItemComposition").hidden=!item||item.stock_mode!=="composition";$("itemDialog").showModal()
  }
  async function uploadItemPhotos(itemId){
    const uploaded={};
    for(let slot=1;slot<=3;slot++){
      const input=$("itemPhotoFile"+slot),file=input.files?.[0];if(!file)continue;
      if(!file.type.startsWith("image/"))throw new Error(`O arquivo do slot ${slot} não é uma imagem.`);
      const extension=(file.name.split(".").pop()||"jpg").toLowerCase().replace(/[^a-z0-9]/g,"")||"jpg",path=`items/${itemId}/photo_${slot}.${extension}`;
      const {error}=await db.storage.from("item-photos").upload(path,file,{upsert:true,contentType:file.type,cacheControl:"3600"});if(error)throw error;
      uploaded[`photo_url_${slot}`]=db.storage.from("item-photos").getPublicUrl(path).data.publicUrl;
    }
    return uploaded
  }
  function openItemPhotos(itemId){const item=state.items.find(entry=>String(entry.id)===String(itemId));if(!item)return;$("photoItemId").value=item.id;$("itemPhotosTitle").textContent=`Gerenciar fotos · ${item.name}`;for(let slot=1;slot<=3;slot++){$("itemPhotoFile"+slot).value="";$("itemPhoto"+slot).value=item[`photo_url_${slot}`]||""}$("itemPhotosDialog").showModal()}
  async function saveItemPhotos(event){event.preventDefault();const itemId=$("photoItemId").value;try{const uploaded=await uploadItemPhotos(itemId),payload={};for(let slot=1;slot<=3;slot++)payload[`photo_url_${slot}`]=uploaded[`photo_url_${slot}`]||$("itemPhoto"+slot).value.trim()||null;const {error}=await db.from("items").update(payload).eq("id",itemId);if(error)throw error;$("itemPhotosDialog").close();toast("Fotos atualizadas.");await loadCatalog()}catch(error){toast(error.message,true)}}
  async function saveItem(event){
    event.preventDefault();
    const id=$("itemId").value,itemKind=$("itemKind").value||"direct",existing=state.items.find(entry=>String(entry.id)===String(id)),payload={name:$("itemName").value.trim(),description:$("itemDescription").value.trim()||null,price:Number($("itemPrice").value),sort_priority:existing?.sort_priority??state.items.length,category_id:$("itemCategory").value||null,stock_mode:itemKind,is_active:$("itemActive").checked};let itemId=id;
    if(!payload.name){toast("Informe o nome do item.",true);return}
    if(id){const {error}=await db.from("items").update(payload).eq("id",id);if(error){toast(error.message,true);return}}
    else{itemId=`${slug(payload.name)}-${crypto.randomUUID().slice(0,4)}`;const {error}=await db.from("items").insert({...payload,id:itemId,stock:0});if(error){toast(error.message,true);return}}
    $("itemDialog").close();toast(id?"Item atualizado.":"Item criado.");await loadCatalog()
  }
  async function deleteItem(){
    const id=$("itemId").value;if(!id||!confirm("Excluir definitivamente este item?"))return;
    const {error}=await db.from("items").delete().eq("id",id);if(error){toast(error.message,true);return}
    $("itemDialog").close();toast("Item excluído.");await loadCatalog()
  }

  function openCategory(id="",parentId=""){const category=state.categories.find(c=>c.id===id);$("categoryForm").reset();$("categoryId").value=category?.id||"";$("categoryDialogTitle").textContent=category?`Editar ${category.name}`:"Nova categoria";$("categoryName").value=category?.name||"";$("categoryParent").innerHTML='<option value="">Raiz</option>'+categoryOptions(category?.id||"");$("categoryParent").value=category?.parent_id||parentId||"";$("categoryDisplay").value=category?.display_mode||"lista";$("categoryComponentPackage").value=category?.component_package_id||"";$("categoryPriority").value=category?.sort_priority??0;$("deleteCategory").hidden=!category;$("categoryDialog").showModal()}
  function uniqueCategoryId(name){const base=slug(name);let candidate=base,index=2;while(state.categories.some(c=>c.id===candidate))candidate=`${base}-${index++}`;return candidate}
  async function saveCategory(event){event.preventDefault();const id=$("categoryId").value,componentPackageId=$("categoryComponentPackage").value||null,pack=componentPackageId?state.packages.find(entry=>String(entry.id)===String(componentPackageId)):null;if(componentPackageId&&(!pack||pack.is_sellable!==true||pack.kind!=="scalable")){toast("Escolha um grupo escalável marcado como vendável.",true);return}const payload={name:$("categoryName").value.trim(),parent_id:$("categoryParent").value||null,display_mode:$("categoryDisplay").value,component_package_id:componentPackageId,sort_priority:Number($("categoryPriority").value)};const request=id?db.from("node_category").update(payload).eq("id",id):db.from("node_category").insert({...payload,id:uniqueCategoryId(payload.name)});const {error}=await request;if(error){toast(/component_package_id|column|schema cache/i.test(error.message||"")?"Aplique a migration 20261010_13_component_package_showcase.sql para associar grupos vendáveis às categorias.":error.message,true);return}$("categoryDialog").close();toast(id?"Categoria atualizada.":"Categoria criada.");await loadCatalog()}
  async function deleteCategory(){const id=$("categoryId").value;if(!id||!confirm("Excluir esta categoria? A operação falhará se ela possuir itens ou subcategorias."))return;const {error}=await db.from("node_category").delete().eq("id",id);if(error){toast(error.message,true);return}$("categoryDialog").close();toast("Categoria excluída.");await loadCatalog()}


  async function loadAdmins(){try{const {data,error}=await db.rpc("list_admins");if(error)throw error;$("adminList").innerHTML=(data||[]).map(a=>`<article class="data-row"><div><strong>${escapeHtml(a.full_name||a.email||a.user_id)}</strong><br><small>${escapeHtml(a.email||a.user_id)}</small></div><span>${new Date(a.granted_at).toLocaleDateString("pt-BR")}</span><span></span><span></span>${a.user_id!==state.session?.user.id?`<button class="button" data-admin-remove="${a.user_id}">Remover</button>`:"<span>Você</span>"}</article>`).join("")}catch(error){$("adminList").innerHTML=`<p>${escapeHtml(error.message)}</p>`}}
  async function loadCustomers(){try{const {data,error}=await db.rpc("list_customer_profiles");if(error)throw error;$("customerList").innerHTML=(data||[]).map(c=>`<article class="data-row"><div><strong>${escapeHtml(c.known_as||c.full_name||c.email||c.user_id)}</strong><br><small>${escapeHtml(c.email||c.user_id)}${c.phone?` · ${escapeHtml(c.phone)}`:""}</small></div><span>${new Date(c.created_at).toLocaleDateString("pt-BR")}</span><span></span><span></span><button class="button danger-button" data-customer-remove="${escapeHtml(c.user_id)}">Apagar cadastro</button></article>`).join("")||"<p>Nenhum cadastro.</p>"}catch(error){$("customerList").innerHTML=`<p>${escapeHtml(error.message)}</p>`}}
  function switchOrderTab(tab){if(![-1,0,1,2].includes(tab))return;state.orderTab=tab;localStorage.setItem("aldoAdminOrdersTab",String(tab));renderOrders();window.scrollTo({top:0,behavior:"smooth"})}
  function switchView(view){if(!viewNames.includes(view))view="home";state.view=view;localStorage.setItem("aldoAdminViewV2",view);if(location.hash!==`#${view}`)location.hash=view;document.querySelectorAll(".view").forEach(x=>x.classList.toggle("active",x.id===view+"View"));document.querySelectorAll("#nav button").forEach(x=>x.classList.toggle("active",x.dataset.view===view));$("viewTitle").textContent=titles[view];$("refresh").hidden=view==="home";$("appView").classList.toggle("orders-mode",view==="orders");$("appView").classList.toggle("home-mode",view==="home");if(orderRefreshTimer){clearInterval(orderRefreshTimer);orderRefreshTimer=null}if(view==="orders")orderRefreshTimer=setInterval(()=>{if(!document.hidden&&state.view==="orders")loadOrders().catch(error=>toast(error.message,true))},10000)}
  async function candidate(id,action){const fn=action==="confirm"?"confirm_whatsapp_candidate":"discard_whatsapp_candidate";const {error}=await db.rpc(fn,{candidate_id:id});if(error)toast(error.message,true);else{toast(action==="confirm"?"Pedido confirmado.":"Candidato descartado.");await Promise.all([loadCandidates(),loadOrders(),loadCatalog()])}}
  async function addAdmin(event){event.preventDefault();const {error}=await db.rpc("grant_admin_by_email",{target_email:$("adminEmail").value.trim()});if(error)toast(error.message,true);else{toast("Administrador adicionado.");event.target.reset();await loadAdmins()}}
  async function removeAdmin(id){const {error}=await db.from("admin_users").delete().eq("user_id",id);if(error)toast(error.message,true);else{toast("Acesso removido.");await loadAdmins()}}
  async function removeCustomerProfile(id){if(!confirm("Apagar os dados de cadastro deste cliente? A conta Google e o histórico de pedidos serão mantidos; no próximo pedido, o cadastro deverá ser preenchido novamente."))return;const {error}=await db.rpc("delete_customer_profile",{target_user:id});if(error)toast(error.message,true);else{toast("Cadastro apagado.");await loadCustomers()}}
  function subscribe(){if(state.liveChannels.length)return;state.liveChannels=[db.channel("admin-orders-live").on("postgres_changes",{event:"*",schema:"public",table:"orders"},loadOrders).subscribe(),db.channel("admin-candidates-live").on("postgres_changes",{event:"*",schema:"public",table:"whatsapp_order_candidates"},loadCandidates).subscribe()]}

  window.addEventListener("hashchange",()=>{const route=location.hash.slice(1);switchView(viewNames.includes(route)?route:"home")});
  $("nav").addEventListener("click",e=>{const button=e.target.closest("[data-view]");if(button){switchView(button.dataset.view);document.querySelector(".view-menu").open=false}});
  $("homeView").addEventListener("click",e=>{const tile=e.target.closest("[data-view]");if(tile)switchView(tile.dataset.view)});
  document.addEventListener("click",e=>{const home=e.target.closest(".home-return");if(home)switchView("home")});
  $("ordersRefresh").addEventListener("click",refreshAll);
  $("ordersTabs").addEventListener("click",e=>{const tab=e.target.closest("[data-order-tab]");if(tab)switchOrderTab(Number(tab.dataset.orderTab))});
  $("orderSettingsOpen").addEventListener("click",()=>$("orderSettingsDialog").showModal());
  $("orderSettingsCancel").addEventListener("click",()=>$("orderSettingsDialog").close());
  $("orderSettingsForm").addEventListener("submit",saveOrderSettings);
  document.addEventListener("keydown",e=>{
    if(state.view!=="orders"||$("orderExpandedDialog").open||$("orderSettingsDialog").open)return;
    if(["INPUT","TEXTAREA","SELECT"].includes(document.activeElement?.tagName))return;
    if(e.key==="ArrowLeft"||e.key==="ArrowRight"){
      e.preventDefault();const tabs=[-1,0,1,2],index=tabs.indexOf(state.orderTab);switchOrderTab(tabs[Math.max(0,Math.min(tabs.length-1,index+(e.key==="ArrowRight"?1:-1)))]);
    }else if(["ArrowDown","ArrowUp","PageDown","PageUp"].includes(e.key)){
      e.preventDefault();window.scrollBy({top:Math.max(100,window.innerHeight*.72)*(["ArrowDown","PageDown"].includes(e.key)?1:-1),behavior:"smooth"});
    }
  });
  const handleOrderAction=e=>{const viewButton=e.target.closest("[data-order-view]");if(viewButton){openOrderDetails(viewButton.dataset.orderView);return}const button=e.target.closest("[data-order]");if(button&&!button.disabled)transitionOrder(button.dataset.order,button.dataset.status)};
  $("ordersBoard").addEventListener("click",handleOrderAction);
  $("deliveryOrders").addEventListener("click",handleOrderAction);
  $("orderExpandedDialog").querySelector(".order-expanded-close").addEventListener("click",()=>$("orderExpandedDialog").close());
  $("stockState").addEventListener("change",renderStock);
  $("stockView").querySelector(".inventory-tabs").addEventListener("click",e=>{const tab=e.target.closest("[data-stock-kind]");if(!tab)return;$("stockKind").value=tab.dataset.stockKind;document.querySelectorAll("[data-stock-kind]").forEach(button=>{const active=button===tab;button.classList.toggle("active",active);button.setAttribute("aria-selected",String(active))});renderStock()});
  $("stockList").addEventListener("change",e=>{const row=e.target.closest(".inventory-row");if(!row)return;const hidden=row.querySelector(".inventory-hidden-input"),finished=row.querySelector(".inventory-finished-input"),stock=row.querySelector(".inventory-stock-input");if(e.target===hidden&&hidden.checked)finished.checked=false;if(e.target===finished&&finished.checked)hidden.checked=false;if((e.target===hidden||e.target===finished)&&!hidden.checked&&!finished.checked&&Number(stock.value)===0)stock.value="1";markInventoryChanged(row)});
  $("stockList").addEventListener("click",e=>{const row=e.target.closest(".inventory-row");if(!row)return;const delta=e.target.closest("[data-stock-delta]");if(delta){const input=row.querySelector(".inventory-stock-input");input.value=String(Math.max(0,Math.trunc(Number(input.value)||0)+Number(delta.dataset.stockDelta)));row.querySelector(".inventory-hidden-input").checked=false;row.querySelector(".inventory-finished-input").checked=Number(input.value)===0;markInventoryChanged(row)}});
  $("saveInventory").addEventListener("click",saveInventoryChanges);
  $("googleLogin").addEventListener("click",login);$("logout").addEventListener("click",logout);$("deniedLogout").addEventListener("click",logout);$("refresh").addEventListener("click",refreshAll);$("nav").addEventListener("click",e=>e.target.closest("button")?.dataset.view&&switchView(e.target.closest("button").dataset.view));$("stockSearch").addEventListener("input",renderStock);$("stockKind").addEventListener("change",renderStock);$("stockAmount").addEventListener("input",updatePreview);$("stockOperation").addEventListener("change",updatePreview);$("stockForm").addEventListener("submit",saveStock);$("cancelStock").addEventListener("click",()=>$("stockDialog").close());$("itemSearch").addEventListener("input",renderItems);$("itemCategoryFilter").addEventListener("change",renderItems);$("componentSearch").addEventListener("input",renderComponents);$("newItem").addEventListener("click",()=>openItem());$("newCategory").addEventListener("click",()=>openCategory());$("itemForm").addEventListener("submit",saveItem);$("categoryForm").addEventListener("submit",saveCategory);$("cancelItem").addEventListener("click",()=>$("itemDialog").close());$("cancelCategory").addEventListener("click",()=>$("categoryDialog").close());$("deleteItem").addEventListener("click",deleteItem);$("deleteCategory").addEventListener("click",deleteCategory);$("adminForm").addEventListener("submit",addAdmin);
  document.addEventListener("click",e=>{const stock=e.target.closest("[data-stock-id]");if(stock)openStock(stock.dataset.stockKind,stock.dataset.stockId);const item=e.target.closest("[data-item-edit]");if(item)openItem(item.dataset.itemEdit);const addItem=e.target.closest("[data-category-add-item]");if(addItem)openItem("",addItem.dataset.categoryAddItem);const category=e.target.closest("[data-category-edit]");if(category)openCategory(category.dataset.categoryEdit);const child=e.target.closest("[data-category-add-child]");if(child)openCategory("",child.dataset.categoryAddChild);const candidateView=e.target.closest("[data-candidate-view]");if(candidateView)openOrderDetails(candidateView.dataset.candidateView);const confirmBtn=e.target.closest("[data-candidate-confirm]");if(confirmBtn)candidate(confirmBtn.dataset.candidateConfirm,"confirm");const discard=e.target.closest("[data-candidate-discard]");if(discard)candidate(discard.dataset.candidateDiscard,"discard");const remove=e.target.closest("[data-admin-remove]");if(remove)removeAdmin(remove.dataset.adminRemove);const customer=e.target.closest("[data-customer-remove]");if(customer)removeCustomerProfile(customer.dataset.customerRemove)});
  $("newPackage").addEventListener("click",()=>openPackage());
  $("packageForm").addEventListener("submit",savePackage);
  $("packagePresentationForm").addEventListener("submit",savePackagePresentations);
  $("cancelPackagePresentations").addEventListener("click",()=>{$("packagePresentationDialog").close();state.activePresentationPackageId=null});
  $("groupComponentsForm").addEventListener("submit",saveGroupComponents);
  $("addGroupComponent").addEventListener("click",addGroupComponent);
  $("cancelGroupComponents").addEventListener("click",()=>{ $("groupComponentsDialog").close();state.activePackageManagerId=null;state.packageComponentDraft=new Map()});
  $("packageRequiresSelection").addEventListener("change",e=>{if(e.target.checked){if(Number($("packageMin").value)<1)$("packageMin").value="1"}else $("packageMin").value="0"});
  $("packageMin").addEventListener("input",e=>{$("packageRequiresSelection").checked=Number(e.target.value)>0});
  $("cancelPackage").addEventListener("click",() => $("packageDialog").close());
  $("deletePackage").addEventListener("click",()=>deletePackage());
  $("groupComponentsList").addEventListener("click",e=>{const newRemove=e.target.closest("[data-new-row-remove]");if(newRemove){newRemove.closest("[data-group-component-row]").remove();return}const remove=e.target.closest("[data-group-component-remove]");if(remove){state.packageComponentDraft.delete(remove.dataset.groupComponentRemove);remove.closest("[data-group-component-row]").remove()}});
  document.addEventListener("click",e=>{const presentation=e.target.closest("[data-package-presentation]");if(presentation){openPackagePresentations(presentation.dataset.packagePresentation);return}const removeGroup=e.target.closest("[data-package-delete]");if(removeGroup){deletePackage(removeGroup.dataset.packageDelete);return}const manage=e.target.closest("[data-package-manage]");if(manage){openGroupComponents(manage.dataset.packageManage);return}const pack=e.target.closest("[data-package-edit]");if(pack)openPackage(pack.dataset.packageEdit)});
  document.addEventListener("click",e=>{const composed=e.target.closest("[data-category-add-composed]");if(composed){openItem("",composed.dataset.categoryAddComposed,"composition");return}const composition=e.target.closest("[data-item-composition]");if(composition){openItemComposition(composition.dataset.itemComposition);return}const photos=e.target.closest("[data-item-photos]");if(photos)openItemPhotos(photos.dataset.itemPhotos)});
  $("itemPackageList").addEventListener("click",e=>{const manage=e.target.closest("[data-item-package-manage]");if(manage)openItemPackageManager(manage.dataset.itemPackageManage)});
  $("itemPackageList").addEventListener("change",async e=>{const toggle=e.target.closest("[data-item-package-toggle]");if(!toggle)return;const packageId=toggle.dataset.itemPackageToggle;toggle.disabled=true;const saved=toggle.checked?await addItemPackage(packageId):await removeItemPackage(packageId);if(!saved)renderItemComposition()});
  $("closeItemComposition").addEventListener("click",()=>$("itemCompositionDialog").close());
  $("itemPhotosForm").addEventListener("submit",saveItemPhotos);$("cancelItemPhotos").addEventListener("click",()=>$("itemPhotosDialog").close());
  $("editItemComposition").addEventListener("click",()=>{const id=$("itemId").value;$("itemDialog").close();openItemComposition(id)});
  $("itemGroupManagerForm").addEventListener("submit",saveItemPackageManager);$("cancelItemGroupManager").addEventListener("click",()=>$("itemGroupManagerDialog").close());
  db.auth.onAuthStateChange((event,session)=>{if(event==="SIGNED_OUT"){state.session=null;show("login");return}if(event==="SIGNED_IN"&&session?.user?.id!==state.session?.user?.id)setTimeout(bootstrap,0)});bootstrap();
})();
