(() => {
  "use strict";
  const config = window.ALDO_ADMIN_CONFIG || {};
  const db = window.supabase.createClient(config.supabaseUrl, config.supabasePublishableKey);
  const $ = (id) => document.getElementById(id);
  const viewNames = ["home","orders","candidates","stock","items","categories","components","customers","admins"];
  const routeView = location.hash.slice(1);
  const savedView = viewNames.includes(routeView) ? routeView : localStorage.getItem("aldoAdminViewV2");
  const savedOrderTab=Number(localStorage.getItem("aldoAdminOrdersTab")||0);
  const state = {session:null,isAdmin:false,items:[],categories:[],components:[],associations:[],orders:[],orderLoadRevision:0,candidates:[],liveChannels:[],booting:false,view:viewNames.includes(savedView)?savedView:"home",inventoryDrafts:new Map(),orderTab:[-1,0,1,2].includes(savedOrderTab)?savedOrderTab:0,autoAcceptSiteOrders:true};
  const titles = {home:"Administração",orders:"Pedidos",candidates:"Confirmações IA",stock:"Inventário",items:"Itens",categories:"Categorias",components:"Componentes",customers:"Cadastros",admins:"Administradores"};
  let orderRefreshTimer=null;
  const displayLabels = {lista:"Lista","lista-dupla":"Lista dupla",grade:"Grade",grid:"Grid legado"};
  const linkLabels = {delta:"Ajustável",scalable:"Escalável",complementary:"Complementar"};

  function toast(message,error=false){const el=$("toast");el.textContent=message;el.style.borderColor=error?"var(--red)":"var(--green)";el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,4200)}
  function money(value){return Number(value||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
  function escapeHtml(value){return String(value??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
  function slug(value){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,40)||"registro"}
  async function query(table,select="*"){const {data,error}=await db.from(table).select(select);if(error)throw error;return data||[]}
  function show(which){$("loadingView").hidden=which!=="loading";$("loginView").hidden=which!=="login";$("deniedView").hidden=which!=="denied";$("appView").hidden=which!=="app"}

  async function bootstrap(){if(state.booting)return;state.booting=true;show("loading");try{const {data:{session}}=await db.auth.getSession();state.session=session;if(!session){show("login");return}const {data,error}=await db.rpc("is_admin");state.isAdmin=!error&&data===true;if(!state.isAdmin){show("denied");return}$("sessionEmail").textContent=session.user.email||"Administrador";await refreshAll();switchView(state.view);subscribe();show("app")}catch(error){show("login");toast(`Não foi possível carregar a sessão: ${error.message}`,true)}finally{state.booting=false}}
  async function login(){await db.auth.signInWithOAuth({provider:"google",options:{redirectTo:location.origin+location.pathname}})}
  async function logout(){await db.auth.signOut();location.reload()}
  async function refreshAll(){try{await Promise.all([loadOrders(),loadCandidates(),loadCatalog(),loadAdmins(),loadCustomers(),loadOrderSettings()])}catch(error){toast(error.message,true)}}

  async function loadOrderSettings(){try{const {data,error}=await db.rpc("get_order_auto_accept");if(error)throw error;state.autoAcceptSiteOrders=data!==false;$("autoAcceptSiteOrders").checked=state.autoAcceptSiteOrders}catch(error){toast(`Configuração de pedidos indisponível: ${error.message}`,true)}}
  async function saveOrderSettings(event){event.preventDefault();const enabled=$("autoAcceptSiteOrders").checked;const {data,error}=await db.rpc("set_order_auto_accept",{p_enabled:enabled});if(error){toast(error.message,true);return}state.autoAcceptSiteOrders=data!==false;$("autoAcceptSiteOrders").checked=state.autoAcceptSiteOrders;$("orderSettingsDialog").close();toast("Configuração salva.")}

  async function loadOrders(){const revision=++state.orderLoadRevision;const orders=await query("orders","*,order_items(*,order_item_components(*))");if(revision!==state.orderLoadRevision)return;state.orders=orders;state.orders.sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));renderOrders()}
  function orderItemMarkup(item,expanded=false){
    const catalogItem=state.items.find(entry=>String(entry.id)===String(item.catalog_item_id||item.item_id))||state.items.find(entry=>entry.name?.trim().toLocaleLowerCase()===String(item.item_name||item.name||"").trim().toLocaleLowerCase());
    const photo=catalogItem?.photo_url_1||catalogItem?.photo_url_2||catalogItem?.photo_url_3;
    const quantity=Math.max(1,Number(item.quantity)||1);
    const rawOptionsText=item.snapshot?.options_text||item.snapshot?.optionsText||item.options_text||item.modifications||"";
    const optionsText=Array.isArray(rawOptionsText)?rawOptionsText.join("|"):rawOptionsText;
    let changes=String(optionsText).split("|").map(part=>part.trim()).filter(Boolean).map(text=>{
      const normalized=text.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase();
      const kind=/^remover\b/.test(normalized)?"remove":/^adicionar\b/.test(normalized)?"add":"other";
      return `<span class="order-change-chip ${kind}">${escapeHtml(text)}</span>`;
    });
    if(!changes.length)changes=(item.order_item_components||[]).filter(component=>{
      const selected=Number(component.snapshot?.per_item_quantity??component.quantity);
      const standard=Number(component.snapshot?.default_quantity??component.free_quantity??0);
      return selected!==standard;
    }).map(component=>{
      const selected=Number(component.snapshot?.per_item_quantity??component.quantity);
      const standard=Number(component.snapshot?.default_quantity??component.free_quantity??0);
      const difference=selected-standard;
      const total=Math.abs(difference)*quantity;
      const prefix=difference>0?"Adicionar":"Remover";
      const amount=total>1?`${total}x `:"";
      return `<span class="order-change-chip ${difference>0?"add":"remove"}">${prefix} ${amount}${escapeHtml(component.component_name)}</span>`;
    });
    const image=photo?`<img src="${escapeHtml(photo)}" alt="" loading="lazy">`:'<span class="order-item-photo" aria-hidden="true"></span>';
    const note=item.notes?`<small>${escapeHtml(item.notes)}</small>`:"";
    const quantityBadge=quantity>1?`<span class="item-quantity-badge" data-quantity="${Math.min(quantity,8)}">${quantity}</span>`:"";
    return `<div class="order-item ${expanded?"expanded-order-item":""}">${image}<div class="order-item-copy"><div class="order-item-title">${quantityBadge}<strong>${escapeHtml(item.item_name||item.name||"Item")}</strong></div>${changes.length?`<div class="order-item-changes">${changes.join("")}</div>`:""}${note}</div></div>`;
  }
  function renderOrders(){
    const pending=state.orders.filter(order=>order.status==="pending_confirmation");
    const pendingCandidates=state.candidates;
    const active=state.orders.filter(order=>["received","confirmed","production"].includes(order.status));
    const deliveryOrders=state.orders.filter(order=>order.status==="delivery");
    const delivered=state.orders.filter(order=>order.status==="delivered").slice().reverse();
    [["pending",pending.length+pendingCandidates.length],["active",active.length],["delivery",deliveryOrders.length],["delivered",delivered.length]].forEach(([key,count])=>{
      const badge=document.querySelector(`[data-order-count="${key}"]`);if(badge)badge.textContent=count;
    });
    $("ordersView").dataset.orderTab=String(state.orderTab);
    document.querySelectorAll("[data-order-tab]").forEach(tab=>{const selected=Number(tab.dataset.orderTab)===state.orderTab;tab.classList.toggle("active",selected);tab.setAttribute("aria-selected",String(selected))});
    const orderCard=(order,tab)=>{
      const address=order.delivery_address||{};
      const location=[address.street,address.landmark,address.address_extra].filter(Boolean).map(escapeHtml).join(" · ");
      const items=(order.order_items||[]).map(item=>orderItemMarkup(item)).join("");
      const generalNote=order.notes?`<p class="order-general-note"><strong>Obs. do pedido:</strong> ${escapeHtml(order.notes)}</p>`:"";
      const canPrepare=["received","confirmed"].includes(order.status),canDeliver=order.status==="production";
      const id=escapeHtml(order.id);
      const actions=tab===-1?`<button class="button order-action review-accept" data-order="${id}" data-status="received" aria-label="Aceitar pedido" title="Aceitar">✓</button><button class="button order-action review-reject" data-order="${id}" data-status="cancelled" aria-label="Recusar pedido" title="Recusar">×</button>`:tab===1?`<button class="button delivery-done icon-action" data-order="${id}" data-status="delivered" aria-label="Marcar como entregue" title="Marcar como entregue"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 6h11v12H3zM14 10h4l3 3v5h-7z"/><circle cx="7.5" cy="19" r="1.5"/><circle cx="18" cy="19" r="1.5"/><path d="m8 11 2 2 4-4"/></svg></button>`:tab===2?"":`<button class="button order-action icon-action" data-order="${id}" data-status="preparing" aria-label="Preparando" title="Preparando" ${canPrepare?"":"disabled"}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 10h16l-1.4 9H5.4L4 10Z"/><path d="M7 7c0-1 1-1 1-2m4 2c0-1 1-1 1-2m4 2c0-1 1-1 1-2M3 21h18"/></svg></button><button class="button order-action icon-action" data-order="${id}" data-status="delivery" aria-label="Saiu para entrega" title="Saiu para entrega" ${canDeliver?"":"disabled"}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 6h11v12H3zM14 10h4l3 3v5h-7z"/><circle cx="7.5" cy="19" r="1.5"/><circle cx="18" cy="19" r="1.5"/><path d="M16 13h4"/></svg></button>`;
      return `<article class="order-row status-${escapeHtml(order.status)}"><div class="order-customer"><strong>${escapeHtml(order.customer_known_as||order.customer_name||"")}</strong>${location?`<small>${location}</small>`:""}<strong class="order-card-total">${money(order.total)}</strong><button class="button view-order-button" data-order-view="${id}">Ver pedido</button></div><div class="order-items">${items}</div><div class="order-actions">${actions}</div>${generalNote}</article>`;
    };
    const candidateCard=candidate=>{
      const detail=candidate.interpreted_order||{};
      const address=detail.delivery_address||{};
      const location=[address.street,address.landmark,address.address_extra].filter(Boolean).map(escapeHtml).join(" · ");
      const items=(Array.isArray(detail.items)?detail.items:[]).map(item=>orderItemMarkup({...item,item_name:item.item_name||item.name,snapshot:item.snapshot||{options_text:item.options_text||item.modifications||""}})).join("");
      const total=Number.isFinite(Number(detail.total))?`<strong class="order-card-total">${money(detail.total)}</strong>`:"";
      const generalNote=detail.notes?`<p class="order-general-note"><strong>Obs. do pedido:</strong> ${escapeHtml(detail.notes)}</p>`:"";
      return `<article class="order-row candidate-order-row status-pending_confirmation"><div class="order-customer"><strong>${escapeHtml(detail.customer_known_as||detail.customer_name||"Pedido WhatsApp")}</strong>${location?`<small>${location}</small>`:""}${total}<button class="button view-order-button" data-candidate-view="${escapeHtml(candidate.id)}">Ver pedido</button></div><div class="order-items">${items}</div><div class="order-actions"><button class="button order-action review-accept" data-candidate-confirm="${escapeHtml(candidate.id)}" aria-label="Confirmar pedido" title="Confirmar">✓</button><button class="button order-action review-reject" data-candidate-discard="${escapeHtml(candidate.id)}" aria-label="Descartar pedido" title="Descartar">×</button></div>${generalNote}</article>`;
    };
    const rows=state.orderTab===-1?[...pending.map(order=>({created_at:order.created_at,html:orderCard(order,-1)})),...pendingCandidates.map(candidate=>({created_at:candidate.created_at,html:candidateCard(candidate)}))].sort((a,b)=>new Date(a.created_at)-new Date(b.created_at)).map(row=>row.html):state.orderTab===1?deliveryOrders.map(order=>orderCard(order,1)):state.orderTab===2?delivered.map(order=>orderCard(order,2)):active.map(order=>orderCard(order,0));
    $("ordersBoard").innerHTML=rows.join("");
    const customerName=order=>escapeHtml(order.customer_known_as||order.customer_name||"");
    const compact=(list)=>list.map(order=>{
      const categoryCounts=new Map();
      (order.order_items||[]).forEach(item=>{
        const category=state.categories.find(entry=>entry.id===state.items.find(catalogItem=>String(catalogItem.id)===String(item.catalog_item_id))?.category_id);
        const categoryName=category?.name||"Sem categoria";
        categoryCounts.set(categoryName,(categoryCounts.get(categoryName)||0)+Number(item.quantity||0));
      });
      const counts=[...categoryCounts].map(([name,quantity])=>`${quantity} ${escapeHtml(name)}`).join(" · ");
      const deliveredAction=list===deliveryOrders?`<button class="button delivery-done icon-action" data-order="${escapeHtml(order.id)}" data-status="delivered" aria-label="Marcar como entregue" title="Marcar como entregue"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 6h11v12H3zM14 10h4l3 3v5h-7z"/><circle cx="7.5" cy="19" r="1.5"/><circle cx="18" cy="19" r="1.5"/><path d="m8 11 2 2 4-4"/></svg></button>`:"";
      const compactState=list===deliveryOrders?"status-delivery":"status-delivered";
      return `<div class="compact-order-name ${compactState} ${deliveredAction?"has-action":""}"><div><strong>${customerName(order)}</strong>${counts?`<small>${counts}</small>`:""}<small class="compact-order-total">${money(order.total)}</small></div>${deliveredAction}</div>`;
    }).join("");
    $("deliveryOrders").innerHTML=compact(deliveryOrders);
    $("deliveredOrders").innerHTML=compact(state.orders.filter(order=>order.status==="delivered").slice().reverse());
  }
  function openOrderDetails(id){
    const order=state.orders.find(entry=>String(entry.id)===String(id));
    if(!order){
      const candidate=state.candidates.find(entry=>String(entry.id)===String(id));if(!candidate)return;
      const detail=candidate.interpreted_order||{},address=detail.delivery_address||{};
      const location=[address.street,address.landmark,address.address_extra].filter(Boolean).map(escapeHtml).join(" · ");
      const items=(Array.isArray(detail.items)?detail.items:[]).map(item=>orderItemMarkup({...item,item_name:item.item_name||item.name,snapshot:item.snapshot||{options_text:item.options_text||item.modifications||""}},true)).join("");
      const notes=detail.notes?`<p class="expanded-order-note"><strong>Obs. do pedido:</strong> ${escapeHtml(detail.notes)}</p>`:"";
      const total=Number.isFinite(Number(detail.total))?`<strong class="expanded-order-total">${money(detail.total)}</strong>`:"";
      $("orderExpandedContent").innerHTML=`<div class="expanded-order-customer"><strong>${escapeHtml(detail.customer_known_as||detail.customer_name||"Pedido WhatsApp")}</strong>${location?`<small>${location}</small>`:""}</div><div class="expanded-order-items">${items}</div>${notes}${total}`;
      $("orderExpandedDialog").showModal();return;
    }
    const address=order.delivery_address||{};
    const location=[address.street,address.landmark,address.address_extra].filter(Boolean).map(escapeHtml).join(" · ");
    const items=(order.order_items||[]).map(item=>orderItemMarkup(item,true)).join("");
    const notes=order.notes?`<p class="expanded-order-note"><strong>Obs. do pedido:</strong> ${escapeHtml(order.notes)}</p>`:"";
    $("orderExpandedContent").innerHTML=`<div class="expanded-order-customer"><strong>${escapeHtml(order.customer_known_as||order.customer_name||"")}</strong>${location?`<small>${location}</small>`:""}</div><div class="expanded-order-items">${items}</div>${notes}<strong class="expanded-order-total">${money(order.total)}</strong>`;
    $("orderExpandedDialog").showModal();
  }

  async function transitionOrder(id,status){if(status==="cancelled"&&!confirm("Recusar este pedido?"))return;if(status==="preparing"){const order=state.orders.find(entry=>String(entry.id)===String(id));if(order?.status==="received"){const confirmation=await db.rpc("transition_order",{target_order:id,next_status:"confirmed"});if(confirmation.error){toast(confirmation.error.message,true);return}}status="production"}const {data,error}=await db.rpc("transition_order",{target_order:id,next_status:status});if(error){toast(error.message,true);return}const updated=Array.isArray(data)?data[0]:data;state.orders=state.orders.map(order=>String(order.id)===String(id)?{...order,...(updated||{}),status:updated?.status||status}:order);renderOrders();await loadOrders()}

  async function loadCandidates(){state.candidates=(await query("whatsapp_order_candidates")).filter(c=>c.status==="pending").sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));renderCandidates()}
  function renderCandidates(){const homeBadge=$("candidateHomeBadge");homeBadge.textContent=state.candidates.length;homeBadge.hidden=!state.candidates.length;$("candidateList").innerHTML=state.candidates.map(c=>`<article class="candidate-card"><h3>Conversa ${escapeHtml(c.conversation_key)}</h3><div class="meta"><span class="pill">Confiança ${c.confidence==null?"—":Math.round(c.confidence*100)+"%"}</span><span>${new Date(c.created_at).toLocaleString("pt-BR")}</span></div><pre>${escapeHtml(JSON.stringify(c.interpreted_order,null,2))}</pre><div class="actions"><button class="button primary" data-candidate-confirm="${c.id}">Confirmar</button><button class="button" data-candidate-discard="${c.id}">Descartar</button></div></article>`).join("")||"<p>Nenhum candidato aguardando confirmação.</p>";renderOrders()}

  async function loadCatalog(){[state.items,state.categories,state.components,state.associations]=await Promise.all([query("items","id,name,description,price,stock,category_id,photo_url_1,photo_url_2,photo_url_3,sort_priority,stock_mode,is_active"),query("node_category","id,name,parent_id,display_mode,sort_priority"),query("composition","id,name,stock,price,is_active,max_quantity,tracks_stock"),query("item_composition_association","id,owner_id,composition_id,link_type,link_value,use_group_disjunction,group_disjunction_index")]);const sort=(a,b)=>(a.sort_priority||0)-(b.sort_priority||0)||a.name.localeCompare(b.name);state.items.sort(sort);state.categories.sort(sort);state.components.sort((a,b)=>a.name.localeCompare(b.name));renderStock();renderItems();renderCategories();renderComponents();renderOrders();populateCategoryControls()}

  function categoryPath(id){const names=[],seen=new Set();let current=state.categories.find(c=>c.id===id);while(current&&!seen.has(current.id)){seen.add(current.id);names.unshift(current.name);current=state.categories.find(c=>c.id===current.parent_id)}return names.join(" › ")||"Sem categoria"}
  function categoryOptions(excludeId=""){return state.categories.filter(c=>c.id!==excludeId).map(c=>`<option value="${escapeHtml(c.id)}">${escapeHtml(categoryPath(c.id))}</option>`).join("")}
  function populateCategoryControls(){const options=categoryOptions();$("itemCategoryFilter").innerHTML='<option value="all">Todas as categorias</option><option value="">Sem categoria</option>'+options;$("itemCategory").innerHTML='<option value="">Sem categoria</option>'+options}
  function childrenOf(parentId){return state.categories.filter(c=>(c.parent_id||null)===(parentId||null))}
  function itemsOf(categoryId){return state.items.filter(i=>(i.category_id||null)===(categoryId||null))}
  function itemMatches(item){const term=$("itemSearch").value.trim().toLocaleLowerCase(),filter=$("itemCategoryFilter").value;return(!term||`${item.name} ${item.description||""}`.toLocaleLowerCase().includes(term))&&(filter==="all"||(item.category_id||"")===filter)}
  function itemCard(item){const image=item.photo_url_1?`<img src="${escapeHtml(item.photo_url_1)}" alt="">`:'<div class="item-placeholder">AL</div>';const associationCount=state.associations.filter(a=>a.owner_id===item.id).length;return `<article class="menu-item-card ${item.is_active===false?"inactive":""}">${image}<div class="menu-item-copy"><div class="menu-item-title"><strong>${escapeHtml(item.name)}</strong><strong>${money(item.price)}</strong></div><p>${escapeHtml(item.description||"Sem descrição")}</p><div class="meta"><span class="pill">${item.stock_mode==="composition"?"Por composição":"Estoque direto"}</span><span>${associationCount} componente(s)</span><span>${item.is_active===false?"Oculto":"Ativo"}</span></div></div><button class="button" data-item-edit="${item.id}">Editar</button></article>`}
  function categoryEditor(category,level=0){const items=itemsOf(category.id).filter(itemMatches),children=childrenOf(category.id);const visible=items.length||children.some(c=>hasVisibleCategory(c));if(!visible&&($("itemSearch").value||$("itemCategoryFilter").value!=="all"))return"";return `<section class="menu-category" style="--depth:${level}"><header><div><span class="eyebrow">${escapeHtml(displayLabels[category.display_mode]||category.display_mode)}</span><h3>${escapeHtml(category.name)}</h3></div><div class="actions"><button class="button" data-category-add-item="${category.id}">+ Item</button><button class="button" data-category-add-child="${category.id}">+ Subcategoria</button><button class="button" data-category-edit="${category.id}">Editar categoria</button></div></header><div class="menu-items">${items.map(itemCard).join("")||'<p class="fine-print">Nenhum item diretamente nesta categoria.</p>'}</div>${children.map(c=>categoryEditor(c,level+1)).join("")}</section>`}
  function hasVisibleCategory(category){return itemsOf(category.id).some(itemMatches)||childrenOf(category.id).some(hasVisibleCategory)}
  function renderItems(){const roots=childrenOf(null);const orphanItems=itemsOf(null).filter(itemMatches);$("itemList").innerHTML=(orphanItems.length?`<section class="menu-category"><header><h3>Sem categoria</h3></header><div class="menu-items">${orphanItems.map(itemCard).join("")}</div></section>`:"")+roots.map(c=>categoryEditor(c)).join("")||"<p>Nenhum item corresponde aos filtros.</p>"}

  function categoryTreeRows(parentId=null,level=0){return childrenOf(parentId).map(c=>`<article class="tree-row" style="--depth:${level}"><div><strong>${escapeHtml(c.name)}</strong><small>${escapeHtml(c.id)} · ${escapeHtml(displayLabels[c.display_mode]||c.display_mode)} · ${itemsOf(c.id).length} item(ns)</small></div><div class="actions"><button class="button" data-category-add-child="${c.id}">+ Subcategoria</button><button class="button" data-category-add-item="${c.id}">+ Item</button><button class="button" data-category-edit="${c.id}">Editar</button></div></article>${categoryTreeRows(c.id,level+1)}`).join("")}
  function renderCategories(){$("categoryTree").innerHTML=categoryTreeRows()||"<p>Nenhuma categoria cadastrada.</p>"}
  function renderComponents(){const term=$("componentSearch").value.trim().toLocaleLowerCase();$("componentList").innerHTML=state.components.filter(c=>!term||c.name.toLocaleLowerCase().includes(term)).map(c=>`<article class="data-row"><div><strong>${escapeHtml(c.name)}</strong><br><small>${c.tracks_stock?"Estoque controlado":"Sem controle de estoque"}</small></div><span>${money(c.price)}</span><span>Saldo ${c.stock}</span><span>${c.is_active===false?"Desativado":"Ativo"}</span><button class="button" data-component-edit="${c.id}">Editar</button></article>`).join("")||"<p>Nenhum componente.</p>"}

  function inventoryKey(kind,id){return `${kind}:${id}`}
  function inventoryBase(x){const hidden=x.kind==="composition"?x.is_active===false:Number(x.stock||0)<0,stock=Math.max(0,Number(x.stock||0));return{kind:x.kind,id:String(x.id),hidden,finished:!hidden&&stock===0,stock}}
  function inventoryValue(x){return state.inventoryDrafts.get(inventoryKey(x.kind,x.id))||inventoryBase(x)}
  function inventoryState(x){const value=inventoryValue(x);return value.hidden?"hidden":value.finished?"finished":"visible"}
  function stockRows(){const term=$("stockSearch").value.trim().toLocaleLowerCase(),kind=$("stockKind").value,status=$("stockState").value;return[...state.items.map(x=>({...x,kind:"item"})),...state.components.map(x=>({...x,kind:"composition"}))].filter(x=>(kind==="all"||x.kind===kind)&&(status==="all"||inventoryState(x)===status)&&`${x.name} ${x.id}`.toLocaleLowerCase().includes(term))}
  function inventoryGroupName(x){return x.kind==="composition"?"Componentes":categoryPath(x.category_id)}
  function inventoryRow(x){const value=inventoryValue(x),changed=state.inventoryDrafts.has(inventoryKey(x.kind,x.id)),photo=x.kind==="item"&&x.photo_url_1?`<img class="inventory-photo" src="${escapeHtml(x.photo_url_1)}" alt="">`:'<div class="inventory-photo item-placeholder">AL</div>';return `<article class="inventory-row ${value.hidden?"is-hidden":""} ${changed?"is-changed":""}" data-inventory-kind="${x.kind}" data-inventory-id="${escapeHtml(x.id)}">${photo}<div class="inventory-name"><strong>${escapeHtml(x.name)}</strong><small>${escapeHtml(x.id)} · ${x.kind==="item"?(x.stock_mode==="composition"?"item por composição":"item direto"):"componente"}</small></div><label class="switch inventory-hidden"><input class="inventory-hidden-input" type="checkbox" ${value.hidden?"checked":""}><span class="switch-track"></span><span class="switch-text">${value.hidden?"Oculto":"Visível"}</span></label><label class="switch inventory-finished"><input class="inventory-finished-input" type="checkbox" ${value.finished?"checked":""}><span class="switch-track"></span><span class="switch-text">${value.finished?"Finalizado":"Disponível"}</span></label><div class="stock-steps"><button type="button" data-stock-delta="-10">-10</button><button type="button" data-stock-delta="-1">−</button><input class="inventory-stock-input" type="number" min="0" step="1" value="${value.stock}" aria-label="Estoque de ${escapeHtml(x.name)}"><button type="button" data-stock-delta="1">+</button><button type="button" data-stock-delta="10">+10</button></div></article>`}
  function updateInventorySaveButton(){const count=state.inventoryDrafts.size;$("inventoryChangeCount").textContent=`(${count})`;$("saveInventory").disabled=count===0}
  function renderStock(){const all=[...state.items.map(x=>({...x,kind:"item"})),...state.components.map(x=>({...x,kind:"composition"}))],rows=stockRows(),groups=new Map;for(const x of rows){const group=inventoryGroupName(x);if(!groups.has(group))groups.set(group,[]);groups.get(group).push(x)}$("stockTotal").textContent=`Itens: ${all.length}`;$("stockVisible").textContent=`Visíveis: ${all.filter(x=>inventoryState(x)==="visible").length}`;$("stockFinished").textContent=`Finalizados: ${all.filter(x=>inventoryState(x)==="finished").length}`;$("stockHidden").textContent=`Ocultos: ${all.filter(x=>inventoryState(x)==="hidden").length}`;$("stockList").innerHTML=[...groups].map(([name,entries])=>`<section class="inventory-group"><h3>${escapeHtml(name)} (${entries.length})</h3>${entries.map(inventoryRow).join("")}</section>`).join("")||'<section class="inventory-group"><h3>Nenhum registro encontrado.</h3></section>';updateInventorySaveButton()}
  function markInventoryChanged(row){const kind=row.dataset.inventoryKind,id=row.dataset.inventoryId,entry=(kind==="item"?state.items:state.components).find(x=>String(x.id)===id),base=inventoryBase({...entry,kind}),draft={kind,id,hidden:row.querySelector(".inventory-hidden-input").checked,finished:row.querySelector(".inventory-finished-input").checked,stock:Math.max(0,Math.trunc(Number(row.querySelector(".inventory-stock-input").value)||0))},changed=draft.hidden!==base.hidden||draft.finished!==base.finished||draft.stock!==base.stock,key=inventoryKey(kind,id);if(changed)state.inventoryDrafts.set(key,draft);else state.inventoryDrafts.delete(key);row.classList.toggle("is-hidden",draft.hidden);row.classList.toggle("is-changed",changed);row.querySelector(".inventory-hidden .switch-text").textContent=draft.hidden?"Oculto":"Visível";row.querySelector(".inventory-finished .switch-text").textContent=draft.finished?"Finalizado":"Disponível";updateInventorySaveButton()}
  async function saveInventoryChanges(){const button=$("saveInventory"),drafts=[...state.inventoryDrafts.entries()];if(!drafts.length)return;button.disabled=true;button.textContent="Salvando...";let failed=0;for(const [key,draft] of drafts){let stock=draft.finished?0:draft.stock;if(draft.kind==="item"&&draft.hidden)stock=-1;const table=draft.kind==="item"?"items":"composition",payload=draft.kind==="item"?{stock}:{stock,is_active:!draft.hidden};const {error}=await db.from(table).update(payload).eq("id",draft.id);if(error)failed+=1;else state.inventoryDrafts.delete(key)}button.innerHTML='Salvar alterações <span id="inventoryChangeCount"></span>';if(failed)toast(`${failed} alteração(ões) não foram salvas.`,true);else toast(`${drafts.length} alteração(ões) salvas.`);await loadCatalog()}
  function openStock(kind,id){const entry=(kind==="item"?state.items:state.components).find(x=>String(x.id)===id);if(!entry)return;$("stockTargetKind").value=kind;$("stockTargetId").value=id;$("stockDialogTitle").textContent=entry.name;$("stockAmount").value="";$("stockReason").value="";$("stockPreview").dataset.current=entry.stock;updatePreview();$("stockDialog").showModal()}
  function updatePreview(){const current=Number($("stockPreview").dataset.current||0),amount=Number($("stockAmount").value||0);const result=$("stockOperation").value==="set"?amount:current-amount;$("stockPreview").textContent=`Saldo atual: ${current} → novo saldo: ${result}`;$("confirmStock").disabled=result<0||!Number.isInteger(amount)}
  async function saveStock(event){event.preventDefault();const payload={target_kind:$("stockTargetKind").value,target_id:$("stockTargetId").value,operation:$("stockOperation").value,amount:Number($("stockAmount").value),reason:$("stockReason").value||null};const {error}=await db.rpc("adjust_inventory",payload);if(error){toast(error.message,true);return}$("stockDialog").close();toast("Estoque atualizado.");await loadCatalog()}

  function associationRows(itemId){const current=new Map(state.associations.filter(a=>a.owner_id===itemId).map(a=>[a.composition_id,a]));return state.components.map(c=>{const a=current.get(c.id);return `<div class="association-row" data-component="${c.id}"><label class="check-row"><input type="checkbox" class="assoc-enabled" ${a?"checked":""}> ${escapeHtml(c.name)}</label><select class="assoc-type"><option value="delta" ${a?.link_type==="delta"?"selected":""}>Ajustável</option><option value="scalable" ${a?.link_type==="scalable"?"selected":""}>Escalável</option><option value="complementary" ${a?.link_type==="complementary"?"selected":""}>Complementar</option></select><input class="assoc-value" type="number" min="0" step="1" value="${a?.link_value??1}" aria-label="Valor padrão de ${escapeHtml(c.name)}"><span>${money(c.price)}</span></div>`}).join("")||"<p>Cadastre componentes primeiro.</p>"}
  function openItem(id="",categoryId=""){const item=state.items.find(x=>x.id===id);$("itemForm").reset();$("itemId").value=item?.id||"";$("itemDialogTitle").textContent=item?`Editar ${item.name}`:"Novo item";$("itemName").value=item?.name||"";$("itemDescription").value=item?.description||"";$("itemPrice").value=item?.price??0;$("itemPriority").value=item?.sort_priority??0;$("itemCategory").innerHTML='<option value="">Sem categoria</option>'+categoryOptions();$("itemCategory").value=item?.category_id||categoryId||"";$("itemStockMode").value=item?.stock_mode||"direct";$("itemStock").value=item?.stock??1;$("itemActive").checked=item?.is_active!==false;$("itemPhoto1").value=item?.photo_url_1||"";$("itemPhoto2").value=item?.photo_url_2||"";$("itemPhoto3").value=item?.photo_url_3||"";$("deleteItem").hidden=!item;$("itemCompositionList").innerHTML=item?associationRows(item.id):'<p class="fine-print">Salve o item primeiro; depois reabra para associar componentes.</p>';$("itemDialog").showModal()}
  async function syncAssociations(itemId){const existing=new Map(state.associations.filter(a=>a.owner_id===itemId).map(a=>[a.composition_id,a]));for(const row of $("itemCompositionList").querySelectorAll(".association-row")){const componentId=row.dataset.component,enabled=row.querySelector(".assoc-enabled").checked,current=existing.get(componentId);if(!enabled&&current){const {error}=await db.from("item_composition_association").delete().eq("id",current.id);if(error)throw error}else if(enabled){const payload={owner_id:itemId,composition_id:componentId,link_type:row.querySelector(".assoc-type").value,link_value:Number(row.querySelector(".assoc-value").value),use_group_disjunction:false,group_disjunction_index:0};const request=current?db.from("item_composition_association").update(payload).eq("id",current.id):db.from("item_composition_association").insert(payload);const {error}=await request;if(error)throw error}}}
  async function uploadItemPhotos(itemId){const uploaded={};for(let slot=1;slot<=3;slot++){const input=$("itemPhotoFile"+slot),file=input.files?.[0];if(!file)continue;if(!file.type.startsWith("image/"))throw new Error(`O arquivo do slot ${slot} não é uma imagem.`);const extension=(file.name.split(".").pop()||"jpg").toLowerCase().replace(/[^a-z0-9]/g,"")||"jpg";const path=`items/${itemId}/photo_${slot}.${extension}`;const {error}=await db.storage.from("item-photos").upload(path,file,{upsert:true,contentType:file.type,cacheControl:"3600"});if(error)throw error;uploaded[`photo_url_${slot}`]=db.storage.from("item-photos").getPublicUrl(path).data.publicUrl}if(Object.keys(uploaded).length){const {error}=await db.from("items").update(uploaded).eq("id",itemId);if(error)throw error}}
  async function saveItem(event){event.preventDefault();const id=$("itemId").value,payload={name:$("itemName").value.trim(),description:$("itemDescription").value.trim()||null,price:Number($("itemPrice").value),sort_priority:Number($("itemPriority").value),category_id:$("itemCategory").value||null,stock_mode:$("itemStockMode").value,stock:Number($("itemStock").value),is_active:$("itemActive").checked,photo_url_1:$("itemPhoto1").value||null,photo_url_2:$("itemPhoto2").value||null,photo_url_3:$("itemPhoto3").value||null};let itemId=id;if(id){const {error}=await db.from("items").update(payload).eq("id",id);if(error){toast(error.message,true);return}}else{itemId=`${slug(payload.name)}-${crypto.randomUUID().slice(0,4)}`;const {error}=await db.from("items").insert({...payload,id:itemId});if(error){toast(error.message,true);return}}try{await uploadItemPhotos(itemId);if(id)await syncAssociations(itemId)}catch(error){toast(`Item salvo, mas uma imagem ou composição falhou: ${error.message}`,true);return}$("itemDialog").close();toast(id?"Item atualizado.":"Item criado. Reabra-o para configurar a composição.");await loadCatalog()}
  async function deleteItem(){const id=$("itemId").value;if(!id||!confirm("Excluir definitivamente este item?"))return;const {error}=await db.from("items").delete().eq("id",id);if(error){toast(error.message,true);return}$("itemDialog").close();toast("Item excluído.");await loadCatalog()}

  function openCategory(id="",parentId=""){const category=state.categories.find(c=>c.id===id);$("categoryForm").reset();$("categoryId").value=category?.id||"";$("categoryDialogTitle").textContent=category?`Editar ${category.name}`:"Nova categoria";$("categoryName").value=category?.name||"";$("categoryParent").innerHTML='<option value="">Raiz</option>'+categoryOptions(category?.id||"");$("categoryParent").value=category?.parent_id||parentId||"";$("categoryDisplay").value=category?.display_mode||"lista";$("categoryPriority").value=category?.sort_priority??0;$("deleteCategory").hidden=!category;$("categoryDialog").showModal()}
  function uniqueCategoryId(name){const base=slug(name);let candidate=base,index=2;while(state.categories.some(c=>c.id===candidate))candidate=`${base}-${index++}`;return candidate}
  async function saveCategory(event){event.preventDefault();const id=$("categoryId").value,payload={name:$("categoryName").value.trim(),parent_id:$("categoryParent").value||null,display_mode:$("categoryDisplay").value,sort_priority:Number($("categoryPriority").value)};const request=id?db.from("node_category").update(payload).eq("id",id):db.from("node_category").insert({...payload,id:uniqueCategoryId(payload.name)});const {error}=await request;if(error){toast(error.message,true);return}$("categoryDialog").close();toast(id?"Categoria atualizada.":"Categoria criada.");await loadCatalog()}
  async function deleteCategory(){const id=$("categoryId").value;if(!id||!confirm("Excluir esta categoria? A operação falhará se ela possuir itens ou subcategorias."))return;const {error}=await db.from("node_category").delete().eq("id",id);if(error){toast(error.message,true);return}$("categoryDialog").close();toast("Categoria excluída.");await loadCatalog()}

  function openComponent(id=""){const c=state.components.find(x=>x.id===id);$("componentForm").reset();$("componentId").value=c?.id||"";$("componentDialogTitle").textContent=c?`Editar ${c.name}`:"Novo componente";$("componentName").value=c?.name||"";$("componentPrice").value=c?.price??0;$("componentStock").value=c?.stock??1;$("componentMax").value=c?.max_quantity??4;$("componentTracks").checked=c?.tracks_stock!==false;$("componentActive").checked=c?.is_active!==false;$("deleteComponent").hidden=!c;$("componentDialog").showModal()}
  async function saveComponent(event){event.preventDefault();const id=$("componentId").value,payload={name:$("componentName").value.trim(),price:Number($("componentPrice").value),stock:Number($("componentStock").value),max_quantity:Number($("componentMax").value),tracks_stock:$("componentTracks").checked,is_active:$("componentActive").checked};const request=id?db.from("composition").update(payload).eq("id",id):db.from("composition").insert(payload);const {error}=await request;if(error){toast(error.message,true);return}$("componentDialog").close();toast(id?"Componente atualizado.":"Componente criado.");await loadCatalog()}
  async function deleteComponent(){const id=$("componentId").value;if(!id||!confirm("Excluir definitivamente este componente?"))return;const {error}=await db.from("composition").delete().eq("id",id);if(error){toast(error.message,true);return}$("componentDialog").close();toast("Componente excluído.");await loadCatalog()}

  async function loadAdmins(){try{const {data,error}=await db.rpc("list_admins");if(error)throw error;$("adminList").innerHTML=(data||[]).map(a=>`<article class="data-row"><div><strong>${escapeHtml(a.full_name||a.email||a.user_id)}</strong><br><small>${escapeHtml(a.email||a.user_id)}</small></div><span>${new Date(a.granted_at).toLocaleDateString("pt-BR")}</span><span></span><span></span>${a.user_id!==state.session?.user.id?`<button class="button" data-admin-remove="${a.user_id}">Remover</button>`:"<span>Você</span>"}</article>`).join("")}catch(error){$("adminList").innerHTML=`<p>${escapeHtml(error.message)}</p>`}}
  async function loadCustomers(){try{const {data,error}=await db.rpc("list_customer_profiles");if(error)throw error;$("customerList").innerHTML=(data||[]).map(c=>`<article class="data-row"><div><strong>${escapeHtml(c.known_as||c.full_name||c.email||c.user_id)}</strong><br><small>${escapeHtml(c.email||c.user_id)}${c.phone?` · ${escapeHtml(c.phone)}`:""}</small></div><span>${new Date(c.created_at).toLocaleDateString("pt-BR")}</span><span></span><span></span><button class="button danger-button" data-customer-remove="${escapeHtml(c.user_id)}">Apagar cadastro</button></article>`).join("")||"<p>Nenhum cadastro.</p>"}catch(error){$("customerList").innerHTML=`<p>${escapeHtml(error.message)}</p>`}}
  function switchOrderTab(tab){if(![-1,0,1,2].includes(tab))return;state.orderTab=tab;localStorage.setItem("aldoAdminOrdersTab",String(tab));renderOrders();$("ordersBoard").scrollTop=0}
  function switchView(view){if(!viewNames.includes(view))view="home";state.view=view;localStorage.setItem("aldoAdminViewV2",view);if(location.hash!==`#${view}`)location.hash=view;document.querySelectorAll(".view").forEach(x=>x.classList.toggle("active",x.id===view+"View"));document.querySelectorAll("#nav button").forEach(x=>x.classList.toggle("active",x.dataset.view===view));$("viewTitle").textContent=titles[view];$("refresh").hidden=view==="home";$("appView").classList.toggle("orders-mode",view==="orders");$("appView").classList.toggle("home-mode",view==="home");if(orderRefreshTimer){clearInterval(orderRefreshTimer);orderRefreshTimer=null}if(view==="orders")orderRefreshTimer=setInterval(()=>{if(!document.hidden&&state.view==="orders")loadOrders().catch(error=>toast(error.message,true))},10000)}
  async function candidate(id,action){const fn=action==="confirm"?"confirm_whatsapp_candidate":"discard_whatsapp_candidate";const {error}=await db.rpc(fn,{candidate_id:id});if(error)toast(error.message,true);else{toast(action==="confirm"?"Pedido confirmado.":"Candidato descartado.");await Promise.all([loadCandidates(),loadOrders(),loadCatalog()])}}
  async function addAdmin(event){event.preventDefault();const {error}=await db.rpc("grant_admin_by_email",{target_email:$("adminEmail").value.trim()});if(error)toast(error.message,true);else{toast("Administrador adicionado.");event.target.reset();await loadAdmins()}}
  async function removeAdmin(id){const {error}=await db.from("admin_users").delete().eq("user_id",id);if(error)toast(error.message,true);else{toast("Acesso removido.");await loadAdmins()}}
  async function removeCustomerProfile(id){if(!confirm("Apagar os dados de cadastro deste cliente? A conta Google e o histórico de pedidos serão mantidos; no próximo pedido, o cadastro deverá ser preenchido novamente."))return;const {error}=await db.rpc("delete_customer_profile",{target_user:id});if(error)toast(error.message,true);else{toast("Cadastro apagado.");await loadCustomers()}}
  function subscribe(){if(state.liveChannels.length)return;state.liveChannels=[db.channel("admin-orders-live").on("postgres_changes",{event:"*",schema:"public",table:"orders"},loadOrders).subscribe(),db.channel("admin-candidates-live").on("postgres_changes",{event:"*",schema:"public",table:"whatsapp_order_candidates"},loadCandidates).subscribe()]}

  window.addEventListener("hashchange",()=>{const route=location.hash.slice(1);switchView(viewNames.includes(route)?route:"home")});
  $("nav").addEventListener("click",e=>{const button=e.target.closest("[data-view]");if(button){switchView(button.dataset.view);document.querySelector(".view-menu").open=false}});
  $("homeView").addEventListener("click",e=>{const tile=e.target.closest("[data-view]");if(tile)switchView(tile.dataset.view)});
  document.addEventListener("click",e=>{const home=e.target.closest(".home-return");if(home)switchView("home")});
  $("ordersRefresh").addEventListener("click",refreshAll);
  $("ordersTabs").addEventListener("click",e=>{const tab=e.target.closest("[data-order-tab]");if(tab)switchOrderTab(Number(tab.dataset.orderTab))});
  $("orderSettingsOpen").addEventListener("click",()=>$("orderSettingsDialog").showModal());
  $("orderSettingsCancel").addEventListener("click",()=>$("orderSettingsDialog").close());
  $("orderSettingsForm").addEventListener("submit",saveOrderSettings);
  document.addEventListener("keydown",e=>{
    if(state.view!=="orders"||$("orderExpandedDialog").open||$("orderSettingsDialog").open)return;
    if(["INPUT","TEXTAREA","SELECT"].includes(document.activeElement?.tagName))return;
    if(e.key==="ArrowLeft"||e.key==="ArrowRight"){
      e.preventDefault();const tabs=[-1,0,1,2],index=tabs.indexOf(state.orderTab);switchOrderTab(tabs[Math.max(0,Math.min(tabs.length-1,index+(e.key==="ArrowRight"?1:-1)))]);
    }else if(e.key==="ArrowDown"||e.key==="ArrowUp"){
      e.preventDefault();$("ordersBoard").scrollBy({top:Math.max(100,$("ordersBoard").clientHeight*.72)*(e.key==="ArrowDown"?1:-1),behavior:"smooth"});
    }
  });
  const handleOrderAction=e=>{const viewButton=e.target.closest("[data-order-view]");if(viewButton){openOrderDetails(viewButton.dataset.orderView);return}const button=e.target.closest("[data-order]");if(button&&!button.disabled)transitionOrder(button.dataset.order,button.dataset.status)};
  $("ordersBoard").addEventListener("click",handleOrderAction);
  $("deliveryOrders").addEventListener("click",handleOrderAction);
  $("orderExpandedDialog").querySelector(".order-expanded-close").addEventListener("click",()=>$("orderExpandedDialog").close());
  $("stockState").addEventListener("change",renderStock);
  $("stockList").addEventListener("change",e=>{const row=e.target.closest(".inventory-row");if(!row)return;const hidden=row.querySelector(".inventory-hidden-input"),finished=row.querySelector(".inventory-finished-input"),stock=row.querySelector(".inventory-stock-input");if(e.target===hidden&&hidden.checked)finished.checked=false;if(e.target===finished&&finished.checked)hidden.checked=false;if((e.target===hidden||e.target===finished)&&!hidden.checked&&!finished.checked&&Number(stock.value)===0)stock.value="1";markInventoryChanged(row)});
  $("stockList").addEventListener("click",e=>{const row=e.target.closest(".inventory-row");if(!row)return;const delta=e.target.closest("[data-stock-delta]");if(delta){const input=row.querySelector(".inventory-stock-input");input.value=String(Math.max(0,Math.trunc(Number(input.value)||0)+Number(delta.dataset.stockDelta)));row.querySelector(".inventory-hidden-input").checked=false;row.querySelector(".inventory-finished-input").checked=Number(input.value)===0;markInventoryChanged(row)}});
  $("saveInventory").addEventListener("click",saveInventoryChanges);
  $("googleLogin").addEventListener("click",login);$("logout").addEventListener("click",logout);$("deniedLogout").addEventListener("click",logout);$("refresh").addEventListener("click",refreshAll);$("nav").addEventListener("click",e=>e.target.closest("button")?.dataset.view&&switchView(e.target.closest("button").dataset.view));$("stockSearch").addEventListener("input",renderStock);$("stockKind").addEventListener("change",renderStock);$("stockAmount").addEventListener("input",updatePreview);$("stockOperation").addEventListener("change",updatePreview);$("stockForm").addEventListener("submit",saveStock);$("cancelStock").addEventListener("click",()=>$("stockDialog").close());$("itemSearch").addEventListener("input",renderItems);$("itemCategoryFilter").addEventListener("change",renderItems);$("componentSearch").addEventListener("input",renderComponents);$("newItem").addEventListener("click",()=>openItem());$("newCategory").addEventListener("click",()=>openCategory());$("newComponent").addEventListener("click",()=>openComponent());$("itemForm").addEventListener("submit",saveItem);$("categoryForm").addEventListener("submit",saveCategory);$("componentForm").addEventListener("submit",saveComponent);$("cancelItem").addEventListener("click",()=>$("itemDialog").close());$("cancelCategory").addEventListener("click",()=>$("categoryDialog").close());$("cancelComponent").addEventListener("click",()=>$("componentDialog").close());$("deleteItem").addEventListener("click",deleteItem);$("deleteCategory").addEventListener("click",deleteCategory);$("deleteComponent").addEventListener("click",deleteComponent);$("adminForm").addEventListener("submit",addAdmin);
  document.addEventListener("click",e=>{const stock=e.target.closest("[data-stock-id]");if(stock)openStock(stock.dataset.stockKind,stock.dataset.stockId);const item=e.target.closest("[data-item-edit]");if(item)openItem(item.dataset.itemEdit);const addItem=e.target.closest("[data-category-add-item]");if(addItem)openItem("",addItem.dataset.categoryAddItem);const category=e.target.closest("[data-category-edit]");if(category)openCategory(category.dataset.categoryEdit);const child=e.target.closest("[data-category-add-child]");if(child)openCategory("",child.dataset.categoryAddChild);const component=e.target.closest("[data-component-edit]");if(component)openComponent(component.dataset.componentEdit);const candidateView=e.target.closest("[data-candidate-view]");if(candidateView)openOrderDetails(candidateView.dataset.candidateView);const confirmBtn=e.target.closest("[data-candidate-confirm]");if(confirmBtn)candidate(confirmBtn.dataset.candidateConfirm,"confirm");const discard=e.target.closest("[data-candidate-discard]");if(discard)candidate(discard.dataset.candidateDiscard,"discard");const remove=e.target.closest("[data-admin-remove]");if(remove)removeAdmin(remove.dataset.adminRemove);const customer=e.target.closest("[data-customer-remove]");if(customer)removeCustomerProfile(customer.dataset.customerRemove)});
  db.auth.onAuthStateChange((event,session)=>{if(event==="SIGNED_OUT"){state.session=null;show("login");return}if(event==="SIGNED_IN"&&session?.user?.id!==state.session?.user?.id)setTimeout(bootstrap,0)});bootstrap();
})();
